# Usages

## Overview

- This page provides a general pipeline for analyzing Lipidomics (LiP) data using the `lipana` package.
- The example data used here is a truncated search report from DIA-NN. This dataset includes three experiment conditions, each with three replicates, and only 1000 proteins are retained.
- The example files are located in the `"path_to/LiPAna/example_data"` directory.

In [6]:
import gzip
import shutil
from pathlib import Path

workspace = Path(".").resolve().parents[1].joinpath("example_data")
print("current workspace:", str(workspace))
# Unzip gzipped files
for file in workspace.glob("*.gz"):
    with gzip.open(file, "rb") as f_in:
        with open(file.with_suffix(""), "wb") as f_out:
            shutil.copyfileobj(f_in, f_out)

current workspace: /home/lishsh/LiPAna_new_version/doc/example_data

In [9]:
import sys

sys.path.append(str(workspace.parent.parent))
import lipana

In [10]:
from time import sleep

import numpy as np
import polars as pl

## Define the Experiment Layout

To annotate the expected report, it is essential to establish an experiment layout. Two methods for accomplishing this are introduced below:

1. Loading from a Text File: You can load a text file containing the experiment layout. An example of such a file might look like this ("replicate" column can be omitted):

|  run | condition | replicate |
| ---: | --------: | --------: |
| run1 |      ctrl |         1 |
| run2 |      ctrl |         2 |
| run3 |      ctrl |         3 |
| run4 |      exp1 |         1 |
| run5 |      exp1 |         2 |
| run6 |      exp1 |         3 |
| run7 |      exp2 |         1 |
| run8 |      exp2 |         2 |

In [11]:
import lipana

from pathlib import Path
workspace = Path("/home/lishsh/LiPAna_new_version/example_data")

exp_layout = lipana.ExperimentLayout.from_file(workspace.joinpath("experiment_layout.txt"))
print("The input file is:")
exp_layout.exp_df

The input file is:

shape: (9, 3)
┌──────────────────────┬───────────┬───────────┐
│ run                  ┆ condition ┆ replicate │
│ ---                  ┆ ---       ┆ ---       │
│ str                  ┆ str       ┆ i64       │
╞══════════════════════╪═══════════╪═══════════╡
│ 20240331_YSJ-HY_2_A  ┆ H2_Y100   ┆ 1         │
│ 20240331_YSJ-HY_2_B  ┆ H2_Y100   ┆ 2         │
│ 20240404_YSJ-HY_2_C  ┆ H2_Y100   ┆ 3         │
│ 20240331_YSJ-HY_5_A  ┆ H5_Y100   ┆ 1         │
│ 20240331_YSJ-HY_5_B  ┆ H5_Y100   ┆ 2         │
│ 20240404_YSJ-HY_5_C  ┆ H5_Y100   ┆ 3         │
│ 20240331_YSJ-HY_30_A ┆ H30_Y100  ┆ 1         │
│ 20240331_YSJ-HY_30_B ┆ H30_Y100  ┆ 2         │
│ 20240404_YSJ-HY_30_C ┆ H30_Y100  ┆ 3         │
└──────────────────────┴───────────┴───────────┘

2. Initializing with a Run-to-Condition Map: Alternatively, you can define the experiment layout by passing a dictionary mapping runs to their respective conditions. This approach is useful if you need to programmatically create or adjust the layout based on specific experiment parameters without relying on an external file

In [51]:
import lipana

exp_layout = lipana.ExperimentLayout.from_run_to_condition_map(
    {
        "20240331_YSJ-HY_2_A": "H2_Y100",
        "20240331_YSJ-HY_2_B": "H2_Y100",
        "20240404_YSJ-HY_2_C_": "H2_Y100",
        "20240331_YSJ-HY_5_A": "H5_Y100",
        "20240331_YSJ-HY_5_B": "H5_Y100",
        "20240404_YSJ-HY_5_C": "H5_Y100",
        "20240331_YSJ-HY_30_A": "H30_Y100",
        "20240331_YSJ-HY_30_B": "H30_Y100",
        "20240404_YSJ-HY_30_C": "H30_Y100",
    }
)

print("This results in the same experiment layout as the previous example, because replicate is incremented from 1")
exp_layout.exp_df

This results in the same experiment layout as the previous example, because replicate is incremented from 1

shape: (9, 3)
┌──────────────────────┬───────────┬───────────┐
│ run                  ┆ condition ┆ replicate │
│ ---                  ┆ ---       ┆ ---       │
│ str                  ┆ str       ┆ i64       │
╞══════════════════════╪═══════════╪═══════════╡
│ 20240331_YSJ-HY_2_A  ┆ H2_Y100   ┆ 1         │
│ 20240331_YSJ-HY_2_B  ┆ H2_Y100   ┆ 2         │
│ 20240404_YSJ-HY_2_C_ ┆ H2_Y100   ┆ 3         │
│ 20240331_YSJ-HY_5_A  ┆ H5_Y100   ┆ 1         │
│ 20240331_YSJ-HY_5_B  ┆ H5_Y100   ┆ 2         │
│ 20240404_YSJ-HY_5_C  ┆ H5_Y100   ┆ 3         │
│ 20240331_YSJ-HY_30_A ┆ H30_Y100  ┆ 1         │
│ 20240331_YSJ-HY_30_B ┆ H30_Y100  ┆ 2         │
│ 20240404_YSJ-HY_30_C ┆ H30_Y100  ┆ 3         │
└──────────────────────┴───────────┴───────────┘

## Load a search report

- This step involves loading and annotating the search report
  - A DIA-NN report can originate from either running DIA-NN standalone or using FragPipe, which integrates DIA-NN for DIA data processing
  - For Spectronaut reports, certain columns are required, and a template for report settings can be generated using: `lipana.report.export_sn_report_setting("path_to_store_the_setting_file.rs")`

### First Load FASTA File(s)

- Before annotating the report, it is essential to load and parse FASTA files for species and sequence information
- `lipana.parse_fasta` will read one or more FASTA files and return a `ParsedFasta` object
  - `fasta_path` can be a path points to a FASTA or a list of paths (`fasta_path=some_path` or `fasta_path=[path1, path2]`)
  - `contam_fasta_path`: this parameter will be useful to strictly exclude potential contaminants. The species of any protein entries in the given file will be annotated as "Contam" instead of its original species, including those presented in `fasta_path`
  - `contaminations`: a list of additional protein entries can be given here, and this parameter can also work alone if `contam_fasta_path` is `None`; this parameter can also be used to define all the entries that from a certain species as contaminants, by providing the species name(s) in the list
- For title parsing
  - Parameter `fasta_title_regex` is `None` by default, and the title will be parsed as the UniProt format ">sp|protein|name_species ...", which will extract "protein" and "species"
  - To set a customized regex for parsing titles, this parameter can be `str` or a list of `str`
  - For example
    - `fasta_title_regex=None` -> UniProt title
    - `fasta_title_regex=r">[^|\s]+?\|(?P<protein>[^|\s]+?)\|[^\s]+?_(?P<species>[^\s]+)[$\s].*"` -> UniProt title but by regex
    - `fasta_title_regex=r">(?P<protein>[^\ ]+).+?Tax_Id=(?P<species>[^\ ]+).*?"` -> A format like ">Q32MB2 TREMBL:Q32MB2 Tax_Id=9606 Gene_Symbol=KRT73"
    - `fasta_title_regex=[regex1, regex2]` -> Try to parse title sequentially until both "protein" and "species" are found. If "protein" can not be found by any regex, will raise error. If "species" can not be found, it will be "unknown", and "protein" will be the first matched one.

In [12]:
parsed_fasta = lipana.parse_fasta(
    fasta_path=workspace.joinpath("human_yeast_contam.fasta"),
    contam_fasta_path=workspace.joinpath("contam.fasta"),
    contaminations=None,
    fasta_title_regex=None,  # Set one or more regex if the title is not UniProt format or there are mixed formats in the FASTA files
    gen_species_to_concat_seqs=True,  # This parameter is useful to annotate species for peptides via a whole protein sequence map, but is time-consuming
    workspace=workspace,
    resume=True,
    write_parsed_fasta=True,
)

### Load and annotate a search report

- Now, load and annotate the search report using the previously set up `ExperimentLayout` and `ParsedFasta`

In [13]:
# The load_search_report methods for DIA-NN and Spectronaut share parameters:
# lipana.DIANNReport.load_search_report(...)
# lipana.SpectronautReport.load_search_report(...)

# Example loading a DIA-NN search report, showing a subset of available parameters
report = lipana.DIANNReport.load_search_report(
    workspace.joinpath("example_diann_report.tsv"),
    exp_layout=exp_layout,
    parsed_fasta=parsed_fasta,
    do_species_annotation=True,  # Set this to True if the experiment includes multiple species
    pre_annotation_filter=(
        (pl.col("Q.Value") < 0.01)
        & (pl.col("Lib.PG.Q.Value") < 0.01)
        & (pl.col("Protein.Group").is_not_null())
        & (pl.col("Precursor.Quantity").is_not_null())
        & (pl.col("Precursor.Quantity") > 1.1)
    ),  # The filters defined here will be applied to the report after loading immediately, and here the 5 rules are default for DIA-NN (if this parameter is not given, these rules will also be applied); for Spectronaut, they are (
    #     (pl.col("PG.ProteinGroups").is_not_null())
    #     & (pl.col("FG.Quantity").is_not_null())
    #     & (pl.col("FG.Quantity") > 1.1)
    # )
    post_annotation_filter=None,  # This parameter can be used to filter the report after annotation
    restricted_cut_sites=("K", "R"),
    expand_to_cut_site_level=True,  # This will make each cut site one row, which means each precursor row will be duplicated
    # modification_map=None,  # This parameter can be either None or a map from software used modification to UniMod. By default, DIA-NN report has None because it use UniMod as default; for `SpectronautReport`, this parameter has a default value as {
    #     "[Acetyl (Protein N-term)]": "(UniMod:1)",
    #     "[Carbamidomethyl (C)]": "(UniMod:4)",
    #     "[Oxidation (M)]": "(UniMod:35)",
    # }
    resume=True,
)
# The variable `report` is now a `SearchReport` object, and basic annotations have been done
report

Search report object with main report shape: (113057, 81)
Number of quantification data: 0
Number of statistics results: 0
Workspace: /home/lishsh/LiPAna_new_version/example_data

## Preparation of Quantification Matrices

- A newly created `SearchReport` object initially contains only a preprocessed search report and associated metadata, and in this section, some quantification matrices will be added to it
- The quantification process can simply involve pivoting the report or aggregating data using methods like topN or maxLFQ

### Use raw reported quantity values

- This approach converts the report into a quantification matrix by using the raw quantity values reported by the software as matrix cells. It is particularly useful for generating precursor-level or protein group-level matrices, since most software will report the quantity values on these two levels
- Additionally, this step demonstrates how to manually attach a customized quantification report to the main report using the `attach_quant_data` method

In [14]:
quant_data = report.attach_quant_data(
    lipana.convert_long_report_to_wide(
        report,
        index_col="precursor",
        column_col="run",
        value_col="precursor_quantity",
        do_log_scale=2,
        pl_filter=(
            ~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)
        ),  # This parameter filters out those peptides mapped to multiple species
        do_unique=True,
    ),
    # These two parameters will be the name of this quantification report, and can be used to retrieve it from the main report object
    # Though they can be named as any strings, it is recommended to use the same name as the entry level and the actually used quantification method
    entry_level="precursor",
    quant_method="precursor_quantity",
)

# To retrieve this object from the main report object, use the following command
quant_data = report.get_quant_data("precursor", "precursor_quantity")

### maxLFQ and topN Methods

- Both maxLFQ and topN methods utilize the same interface through the `SearchReport.construct_and_attach_quant_data` method, featuring convenient designs to handle more complex scenarios
- The following examples will concentrate on maxLFQ; topN can be configured by setting parameters like `method="top3"` or `method="top1"`, etc.

#### Peptide matrix from precursor MS2 via maxLFQ

- This example will do maxLFQ on precursor quantities to get a peptide level matrix

In [15]:
quant_data = report.construct_and_attach_quant_data(
    quant_name="peptide_quant_by_maxlfq_from_prec",  # This parameter will be the name of quantification method for this quantification report, and can be used to retrieve it from the main report object
    method="maxlfq",
    filter_condition=(~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)),
    run_col="run",
    primary_entry_col="stripped_peptide",  # This parameter not only define the primary (target) entry level, but also the first name to retrieve the generated matrix from the main report object
    low_level_entry_col="precursor",
    base_quant_col="precursor_quantity",
    require_expansion=False,
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

MaxLFQ estimation via iq for /tmp/tmp2vwk1u_d.txt
Removing low intensities...

Output to /tmp/tmp2vwk1u_d.txt-iq_output.txt

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmp2vwk1u_d.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...

# lines read (excluding headers)      = 55844
# quantitative values after filtering = 55844

# samples  = 9
# proteins = 9577
nrow = 55844, # proteins = 9577, # samples = 9
Using 95 threads...
0%
5%
10%
15%
20%
25%
30%
35%
40%
45%
50%
55%
60%
66%
71%
76%
81%
87%
92%
97%
Completed.

#### Peptide matrix from prec MS1 and prec MS2 via maxLFQ

- The quantities of base level entries can also be from multiple sources
- The following example will use maxLFQ to aggregate quantities from two levels: precursor MS1 and precursor MS2

In [16]:
quant_data = report.construct_and_attach_quant_data(
    quant_name="peptide_quant_by_maxlfq_from_ms1ms2",
    method="maxlfq",
    filter_condition=(~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)),
    run_col="run",
    primary_entry_col="stripped_peptide",
    low_level_entry_col=("precursor", "precursor"),
    base_quant_col=("precursor_quantity", "precursor_quantity_ms1"),
    require_expansion=(False, False),
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

MaxLFQ estimation via iq for /tmp/tmpllcp0prr.txt
Removing low intensities...

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmpllcp0prr.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...

# lines read (excluding headers)      = 111685
# quantitative values after filtering = 111685

# samples  = 9
# proteins = 9577
nrow = 111685, # proteins = 9577, # samples = 9
Using 95 threads...
0%
5%
10%
15%
21%
27%
32%
38%
43%
49%
55%
61%
66%
71%
77%
82%
87%
92%
98%
Completed.

Output to /tmp/tmpllcp0prr.txt-iq_output.txt

#### Peptide matrix from prec MS1, prec MS2, and fragments, via maxLFQ

- The following example shows a more complicated case, which uses maxLFQ to aggregate quantities from three levels: precursor MS1, precursor MS2, and fragments (the fragment quantity values in the DIA-NN tsv report is in one table cell joined by ";" for each row)

In [17]:
quant_data = report.construct_and_attach_quant_data(
    quant_name="peptide_quant_by_maxlfq_from_ms1ms2frag",
    method="maxlfq",
    filter_condition=(~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)),
    run_col="run",
    primary_entry_col="stripped_peptide",
    low_level_entry_col=("precursor", "precursor", "Fragment.Info"),
    base_quant_col=("precursor_quantity", "precursor_quantity_ms1", "Fragment.Quant.Raw"),
    require_expansion=(False, False, ";"),
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

MaxLFQ estimation via iq for /tmp/tmp6vuvahnl.txt

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmp6vuvahnl.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...

# lines read (excluding headers)      = 701484
# quantitative values after filtering = 701484

# samples  = 9
# proteins = 9577

Removing low intensities...

nrow = 701484, # proteins = 9577, # samples = 9
Using 95 threads...
0%
5%
10%
15%
22%
28%
33%
38%
44%
49%
55%
61%
66%
71%
77%
84%
90%
95%
Completed.

Output to /tmp/tmp6vuvahnl.txt-iq_output.txt

#### Non-restricted cut site from precursor MS2+MS1

- Sometimes, the quantity values should be aggregated from a filtered report
- The following in-one-step example will generate a cut site level matrix, where the cut sites are only non-restricted
  - Whether a cut site is restricted has been annotated via the parameter `restricted_cut_sites` in method `load_search_report` (in this doc, it's `lipana.DIANNReport.load_search_report(..., restricted_cut_sites=("K", "R"), ...)`)
  - Besides the filtering for site annotation `(~pl.col("cut_site_is_restricted"))`, there is also a filter  for peptide, because the C-term of a cut site can be the second residue of a protein, which would be surrounded by first "M" and the third any residue. Here the cut site will be annotated as "non-restricted" if the third residue is K/R, but it's hard to say if the cleavage between protein N-term "M" and the second residue is caused during translation or by a non-restricted enzyme. Further restraining peptide to be semi-specific will address this problem by filtering out such peptides at the protein N-term.

In [18]:
quant_data = report.construct_and_attach_quant_data(
    quant_name="nonrestricted_cut_site_by_maxlfq_from_prec",
    method="maxlfq",
    filter_condition=(
        (~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))
        & (pl.col("peptide_enzymatic_specificity") == "semi_specific")
        & (~pl.col("cut_site_is_restricted"))
    ),
    run_col="run",
    primary_entry_col="cut_site",
    low_level_entry_col=("precursor", "precursor"),
    base_quant_col=("precursor_quantity", "precursor_quantity_ms1"),
    require_expansion=(False, False),
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmpio30a3hr.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...

# lines read (excluding headers)      = 52579
# quantitative values after filtering = 52579

# samples  = 9
# proteins = 4116
nrow = 52579, # proteins = 4116, # samples = 9
Using 95 threads...
0%
5%
10%
15%
21%
26%
31%
37%
43%
54%
59%
65%
70%
76%
81%
86%
92%
98%
Completed.

MaxLFQ estimation via iq for /tmp/tmpio30a3hr.txt
Removing low intensities...

Output to /tmp/tmpio30a3hr.txt-iq_output.txt

### Utilities on quantification report

- The quantification matrix generated from the above sections is actually an object `EntryQuantificationReport`, which has many handful functions

In [19]:
# If the generated object is not explicitly assigned to a variable, can use the following way to get from main report object
quant_data = report.get_quant_data("precursor", "precursor_quantity")

# The following three methods will attach new columns to the dataframe stored in the quantification report object
quant_data.calc_cv(cond="all", min_reps=2, temp_reverse_log_scale=2, new_colname_pattern="{cond}_cv_{min_reps}reps")
quant_data.count_detected_replicates(new_colname_pattern="{cond}_detected_reps")
quant_data.calc_ratio(
    base_cond="H5_Y100",
    is_log=True,
    temp_reverse_log_scale=2,
    div_method="agg_and_divide",
    agg_method="mean",
    new_colname_pattern="ratio_{cond1}_to_{cond2}",
)

shape: (10_303, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ precursor ┆ 20240331_ ┆ 20240404_ ┆ 20240404_ ┆ … ┆ H5_Y100_d ┆ H30_Y100_ ┆ ratio_H2_ ┆ ratio_H3 │
│ ---       ┆ YSJ-HY_30 ┆ YSJ-HY_2_ ┆ YSJ-HY_5_ ┆   ┆ etected_r ┆ detected_ ┆ Y100_to_H ┆ 0_Y100_t │
│ str       ┆ _A        ┆ C         ┆ C         ┆   ┆ eps       ┆ reps      ┆ 5_Y100    ┆ o_H5_Y10 │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 0        │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ i8        ┆ i8        ┆ f32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ AQNIDYDKL ┆ 14.837064 ┆ 14.921881 ┆ 14.924777 ┆ … ┆ 3         ┆ 3         ┆ 0.171129  ┆ -0.16578 │
│ IK/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ GAGKPNSSA ┆ 15.141305 ┆ 14.765122 ┆ 15.500525 ┆ … ┆ 3         ┆ 3         ┆ -0.042147 ┆ 0.108213 │
│ VAILETF/2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SNTTATKEE ┆ 13.460197 ┆ 14.085488 ┆ 14.036002 ┆ … ┆ 3         ┆ 2         ┆ -0.120421 ┆ -0.41280 │
│ FDDQLK/3  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ TGDVEDSTV ┆ 17.339526 ┆ 13.270021 ┆ 14.576235 ┆ … ┆ 3         ┆ 3         ┆ -1.650101 ┆ 2.5644   │
│ LK/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RSTLDPVEK ┆ 20.203632 ┆ 20.667521 ┆ 20.674458 ┆ … ┆ 3         ┆ 3         ┆ -0.019343 ┆ -0.07991 │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ VAVAIPNRP ┆ null      ┆ null      ┆ null      ┆ … ┆ 0         ┆ 1         ┆ NaN       ┆ NaN      │
│ PDAVLTDTT ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SLNQAALYR ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /4        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ YGGPNHIVG ┆ 13.951588 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 1         ┆ NaN       ┆ NaN      │
│ SPFK/3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VKEQDYLC( ┆ null      ┆ null      ┆ null      ┆ … ┆ 0         ┆ 1         ┆ NaN       ┆ NaN      │
│ UniMod:4) ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ HVYVR/3   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ NDFAIHTLK ┆ null      ┆ null      ┆ null      ┆ … ┆ 0         ┆ 1         ┆ NaN       ┆ NaN      │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IGESWVITE ┆ null      ┆ null      ┆ null      ┆ … ┆ 0         ┆ 1         ┆ NaN       ┆ NaN      │
│ GR/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

- Because main report and quantification report are related, the annotation and filtering of quantification report can be done by borrowing data from the main report
- The following method will return a new dataframe instead of updating the dataframe stored in the object

In [20]:
report.get_quant_data(
    entry_name="precursor",
    quant_name="precursor_quantity",
    main_df_entry_filter=(
        (~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))
        & (pl.col("peptide_enzymatic_specificity") == "semi_specific")
    ),
    quant_df_filter=None,
    annotation_cols="protein_group",
)

shape: (4_761, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ precursor ┆ 20240331_ ┆ 20240404_ ┆ 20240404_ ┆ … ┆ H30_Y100_ ┆ ratio_H2_ ┆ ratio_H30 ┆ protein_ │
│ ---       ┆ YSJ-HY_30 ┆ YSJ-HY_2_ ┆ YSJ-HY_5_ ┆   ┆ detected_ ┆ Y100_to_H ┆ _Y100_to_ ┆ group    │
│ str       ┆ _A        ┆ C         ┆ C         ┆   ┆ reps      ┆ 5_Y100    ┆ H5_Y100   ┆ ---      │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ i8        ┆ f32       ┆ f32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GAGKPNSSA ┆ 15.141305 ┆ 14.765122 ┆ 15.500525 ┆ … ┆ 3         ┆ -0.042147 ┆ 0.108213  ┆ P40202   │
│ VAILETF/2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SNTTATKEE ┆ 13.460197 ┆ 14.085488 ┆ 14.036002 ┆ … ┆ 2         ┆ -0.120421 ┆ -0.412809 ┆ P10592   │
│ FDDQLK/3  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RSTLDPVEK ┆ 20.203632 ┆ 20.667521 ┆ 20.674458 ┆ … ┆ 3         ┆ -0.019343 ┆ -0.079913 ┆ P10592   │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VKPVGIVVP ┆ 11.565403 ┆ 10.710749 ┆ 12.065379 ┆ … ┆ 3         ┆ -0.779027 ┆ 0.065343  ┆ P47912   │
│ NLGHL/3   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ YDTDVFTPL ┆ null      ┆ 10.493862 ┆ 11.40034  ┆ … ┆ 2         ┆ 0.155056  ┆ 1.305091  ┆ P40825   │
│ FER/2     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ LTPTQGSYT ┆ 12.932636 ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ Q9Y2T2   │
│ FDPVTK/2  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TVDKDQSIA ┆ 13.72056  ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ P04844   │
│ PK/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TTPSFVGFT ┆ null      ┆ 12.659182 ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ P10592   │
│ D/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DYMVGSYGP ┆ null      ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ P52565   │
│ R/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VKEQDYLC( ┆ null      ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ O15498   │
│ UniMod:4) ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ HVYVR/3   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
quant_data = report.get_quant_data("precursor", "precursor_quantity")
quant_data.attach_annotation_via_entry(
    "protein_group", persist=True
)  # Set `persistent` to True will update the dataframe stored in the object
quant_data.filter_entry_by_main_report(
    main_report_filter=(~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))
    & (pl.col("peptide_enzymatic_specificity") == "semi_specific")
)

shape: (4_761, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ precursor ┆ 20240331_ ┆ 20240404_ ┆ 20240404_ ┆ … ┆ H30_Y100_ ┆ ratio_H2_ ┆ ratio_H30 ┆ protein_ │
│ ---       ┆ YSJ-HY_30 ┆ YSJ-HY_2_ ┆ YSJ-HY_5_ ┆   ┆ detected_ ┆ Y100_to_H ┆ _Y100_to_ ┆ group    │
│ str       ┆ _A        ┆ C         ┆ C         ┆   ┆ reps      ┆ 5_Y100    ┆ H5_Y100   ┆ ---      │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ i8        ┆ f32       ┆ f32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GAGKPNSSA ┆ 15.141305 ┆ 14.765122 ┆ 15.500525 ┆ … ┆ 3         ┆ -0.042147 ┆ 0.108213  ┆ P40202   │
│ VAILETF/2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SNTTATKEE ┆ 13.460197 ┆ 14.085488 ┆ 14.036002 ┆ … ┆ 2         ┆ -0.120421 ┆ -0.412809 ┆ P10592   │
│ FDDQLK/3  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ RSTLDPVEK ┆ 20.203632 ┆ 20.667521 ┆ 20.674458 ┆ … ┆ 3         ┆ -0.019343 ┆ -0.079913 ┆ P10592   │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VKPVGIVVP ┆ 11.565403 ┆ 10.710749 ┆ 12.065379 ┆ … ┆ 3         ┆ -0.779027 ┆ 0.065343  ┆ P47912   │
│ NLGHL/3   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ YDTDVFTPL ┆ null      ┆ 10.493862 ┆ 11.40034  ┆ … ┆ 2         ┆ 0.155056  ┆ 1.305091  ┆ P40825   │
│ FER/2     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ LTPTQGSYT ┆ 12.932636 ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ Q9Y2T2   │
│ FDPVTK/2  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TVDKDQSIA ┆ 13.72056  ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ P04844   │
│ PK/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TTPSFVGFT ┆ null      ┆ 12.659182 ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ P10592   │
│ D/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DYMVGSYGP ┆ null      ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ P52565   │
│ R/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VKEQDYLC( ┆ null      ┆ null      ┆ null      ┆ … ┆ 1         ┆ NaN       ┆ NaN       ┆ O15498   │
│ UniMod:4) ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ HVYVR/3   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Statistics

- The `lipana` package provides several built-in functions that users can chain together to build custom statistical pipelines. For convenience, the package also includes some wrapper functions that provides pre-defined pipeline.
- This section demonstrates how to use these pre-defined pipelines for performing statistical tests.
- Note (missing value): The `lipana.do_stats_pipe_direct` function includes an optional `mv_config` parameter, which defaults to `None`.
  - Default Behavior (`mv_config=None`): If `mv_config` is not specified or is set to `None`, the input data is filtered first based on the `min_rep_count` threshold before any statistical testing occurs.
  - Using Missing Value Handlers: You can set `mv_config` to an instance (or a list of instances) of `AbstractPairwiseMissingValueHandler`. Examples include: `FullEmptyFillingMissingValueHandler(min_rep_count=3)` and `NormalDistSamplingMissingValueHandler(min_rep_count=3, do_imputation_for_rep_range=(1, 2), log_scale_minmax_diff=1)`. When a handler is provided, missing value processing is performed first, and the `min_rep_count` requirement is checked afterward.
  - Example Handler Usage: The examples below utilize `FullEmptyFillingMissingValueHandler(min_rep_count=3)`. This handler imputes a value of 0 (on the log scale) for entries where one condition lacks detected replicates, provided the other condition in the pair has at least 3 detected replicates (`>= min_rep_count`).
  - Disabling Imputation: To disable specific missing value filling or imputation while still potentially using the handler structure, set `mv_config` to `lipana.NullMissingValueHandler()`. Filtering will still be based on `min_rep_count` after this (null) handling step.
- Note (aggregation): The `lipana.do_stats_pipe_agg` function uses the `pipeline` parameter to control how results are aggregated from a base level (e.g., peptides) to a target level (e.g., proteins or cut sites). Specify one of the following options for the `pipeline` parameter:
  - `"sel_min_p"`: Selects the single base-level entry with the minimum p-value for each target-level entry.
  - `"sel_min2_p"`, `"sel_min3_p"`, ...: Selects the top 2, 3, etc., base-level entries with the lowest p-values for each target-level entry.
  - `"combine_p"`: Combines p-values from all associated base-level entries for each target-level entry using Fisher's method. The reported fold change (FC) will be the median FC among the combined base-level entries.
  - Pipelines with `_direction_check` Suffix (e.g., `"sel_min_p_direction_check"`, `"combine_p_direction_check"`): These pipelines first evaluate the directionality (sign of the t-statistic in the predefined pipelines) of fold changes for all base entries mapping to a target entry. They determine if there is a majority direction (positive or negative). Only the base entries matching this majority direction are considered for the subsequent selection or combination step.
- Note (significant selection): After hypothesis testing (and potential aggregation), the `lipana.stats.do_significant_selection` function can be used to annotate whether a target entry is significant, based on specified rules.
  - Generally, you only need to set the `rules` parameter to one or a list of `lipana.stats.SignificantRule` instances, which define the thresholds and pre-filtering conditions used to determine if an entry is significant.
  - To meet the potential requirement that more than one significant detection at the base level is needed to support the significance of a target entry, `requires_n_passed` can be set to a value greater than 1. In this case, `target` will be used as the grouping key to count significant base entries per target.

### Example 1: Test on Fully-Specific Stripped Peptides

This example performs hypothesis tests directly on the quantification data for fully-specific stripped peptides. The results remain at the peptide level.

#### Performing Hypothesis Tests on Fully-Specific Stripped Peptides

- First, we select the fully-specific peptides from the complete search report, and then perform hypothesis tests on this subset.

In [25]:
design = lipana.ComparisonDesign(exp_layout, (("H2_Y100", "H5_Y100"), ("H30_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

filters = (pl.col("peptide_enzymatic_specificity") == "fully_specific") & (
    pl.col("mapped_species_from_peptide").is_in(("HUMAN", "YEAST"))
)

stats_fully_pep = lipana.stats.pipe.do_stats_pipe_direct(
    qdf=report.get_quant_data(
        entry_name="stripped_peptide",
        quant_name="peptide_quant_by_maxlfq_from_ms1ms2",
        main_df_entry_filter=filters,
    ),  # Note here no need to call `.df` because the requirement of filtering will make this function return a dataframe, instead of a `EntryQuantificationReport` object
    design=design,
    entry_level="stripped_peptide",
    mv_config=lipana.FullEmptyFillingMissingValueHandler(3),
    min_rep_count=3,
    annotation_df=report.df.filter(filters),
    group_entry_level="protein_group",  # Note this parameter is given because FDR control also can be done on the protein level
    annotation_cols=[
        "peptide_start_position",
        "peptide_end_position",
        "prev_aa",
        "next_aa",
        "peptide_n_term_aa",
        "peptide_c_term_aa",
        "nterm_enzymatic_specificity",
        "cterm_enzymatic_specificity",
        "peptide_enzymatic_specificity",
        "n_cut_site",
        "c_cut_site",
        "mapped_species_from_peptide",
    ],
    return_chains=False,
)
sleep(0.1)
print(f"First 5 rows of the result (total size: {stats_fully_pep.shape}):")
stats_fully_pep.head(5)

design.pairwise_comparisons = (('H2_Y100', 'H5_Y100'), ('H30_Y100', 'H5_Y100'))

Quantification file: /tmp/tmp5a6zgdi1.txt
All defined comparison pairs: c("H2_Y100", "H5_Y100")
Available comparison pairs: c("H2_Y100", "H5_Y100")
Comparing H2_Y100 vs H5_Y100
Output to /tmp/tmp5a6zgdi1.txt-limma_output.txt
Quantification file: /tmp/tmpxyatj5qn.txt
All defined comparison pairs: c("H30_Y100", "H5_Y100")
Available comparison pairs: c("H30_Y100", "H5_Y100")
Comparing H30_Y100 vs H5_Y100
Output to /tmp/tmpxyatj5qn.txt-limma_output.txt

First 5 rows of the result (total size: (10126, 28)):

shape: (5, 28)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ peptide_e ┆ n_cut_sit ┆ c_cut_sit ┆ mapped_sp │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ nzymatic_ ┆ e         ┆ e         ┆ ecies_fro │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ specifici ┆ ---       ┆ ---       ┆ m_peptide │
│ str       ┆ f64       ┆          ┆           ┆   ┆ ty        ┆ str       ┆ str       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ ---       ┆           ┆           ┆ str       │
│           ┆           ┆          ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -150.8905 ┆ … ┆ fully_spe ┆ Q8WUW1-59 ┆ Q8WUW1-67 ┆ HUMAN     │
│           ┆ 2         ┆          ┆ 13        ┆   ┆ cific     ┆ _60       ┆ _68       ┆           │
│ AGAFEHLPS ┆ -13.48500 ┆ 6.742503 ┆ -145.8312 ┆ … ┆ fully_spe ┆ Q13641-13 ┆ Q13641-14 ┆ HUMAN     │
│ LR        ┆ 6         ┆          ┆ 44        ┆   ┆ cific     ┆ 4_135     ┆ 5_146     ┆           │
│ QMADTGKLN ┆ -13.45295 ┆ 6.72648  ┆ -145.6907 ┆ … ┆ fully_spe ┆ Q00839-54 ┆ Q00839-55 ┆ HUMAN     │
│ TLLQR     ┆ 9         ┆          ┆ 79        ┆   ┆ cific     ┆ 4_545     ┆ 8_559     ┆           │
│ LQDLQGEKD ┆ -13.04591 ┆ 6.522955 ┆ -140.9106 ┆ … ┆ fully_spe ┆ O60610-51 ┆ O60610-52 ┆ HUMAN     │
│ ALHSEK    ┆           ┆          ┆ 85        ┆   ┆ cific     ┆ 2_513     ┆ 7_528     ┆           │
│ LTEELKEQM ┆ -12.95668 ┆ 6.478341 ┆ -135.4388 ┆ … ┆ fully_spe ┆ Q14683-68 ┆ Q14683-69 ┆ HUMAN     │
│ K         ┆ 2         ┆          ┆ 94        ┆   ┆ cific     ┆ 0_681     ┆ 0_691     ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Selecting Significant Detections (General Purpose)

- In a typical experiment, significant detections might be defined as having a fold change (FC) greater than 1.5 or less than 1/1.5, combined with an adjusted p-value below 0.05.
- This selection can be achieved using the following commands.

In [26]:
stats_fully_pep = lipana.stats.do_significant_selection(
    stats_fully_pep,
    rules=lipana.stats.SignificantRule(
        greater_than=None,
        less_than=("adj_pvalue_group_wise", 0.05),
        gt_value_or_lt_negate=(
            "log2_fc_limma",
            np.log2(1.5),
        ),  # note the values defined in this paramter will be expand to (`> value` or `< -value`)
        equal_to=None,
        filter_condition=None,
    ),
    requires_n_passed=1,
    target=None,
    mark_col="significant",
)
filtered = stats_fully_pep.filter(pl.col("significant"))
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (2228, 29)):

shape: (5, 29)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ n_cut_sit ┆ c_cut_sit ┆ mapped_sp ┆ significa │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ e         ┆ e         ┆ ecies_fro ┆ nt        │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ ---       ┆ m_peptide ┆ ---       │
│ str       ┆ f64       ┆          ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ bool      │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ str       ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -150.8905 ┆ … ┆ Q8WUW1-59 ┆ Q8WUW1-67 ┆ HUMAN     ┆ true      │
│           ┆ 2         ┆          ┆ 13        ┆   ┆ _60       ┆ _68       ┆           ┆           │
│ AGAFEHLPS ┆ -13.48500 ┆ 6.742503 ┆ -145.8312 ┆ … ┆ Q13641-13 ┆ Q13641-14 ┆ HUMAN     ┆ true      │
│ LR        ┆ 6         ┆          ┆ 44        ┆   ┆ 4_135     ┆ 5_146     ┆           ┆           │
│ QMADTGKLN ┆ -13.45295 ┆ 6.72648  ┆ -145.6907 ┆ … ┆ Q00839-54 ┆ Q00839-55 ┆ HUMAN     ┆ true      │
│ TLLQR     ┆ 9         ┆          ┆ 79        ┆   ┆ 4_545     ┆ 8_559     ┆           ┆           │
│ LQDLQGEKD ┆ -13.04591 ┆ 6.522955 ┆ -140.9106 ┆ … ┆ O60610-51 ┆ O60610-52 ┆ HUMAN     ┆ true      │
│ ALHSEK    ┆           ┆          ┆ 85        ┆   ┆ 2_513     ┆ 7_528     ┆           ┆           │
│ LTEELKEQM ┆ -12.95668 ┆ 6.478341 ┆ -135.4388 ┆ … ┆ Q14683-68 ┆ Q14683-69 ┆ HUMAN     ┆ true      │
│ K         ┆ 2         ┆          ┆ 94        ┆   ┆ 0_681     ┆ 0_691     ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

- Note that the parameter `gt_value_or_lt_negate` will do an "or" combination by chaining two expressions `(> value) | (< -value)`, and this can be more explicitly defined by providing two rules for the `rules` parameter of `do_significant_selection`
- The following command has the same effect as the above one

In [27]:
stats_fully_pep = lipana.stats.do_significant_selection(
    stats_fully_pep,
    rules=[
        lipana.stats.SignificantRule(
            greater_than=("log2_fc_limma", np.log2(1.5)),
            less_than=("adj_pvalue_group_wise", 0.05),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=None,
        ),
        lipana.stats.SignificantRule(
            greater_than=None,
            less_than=(("adj_pvalue_group_wise", 0.05), ("log2_fc_limma", -np.log2(1.5))),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=None,
        ),
    ],
    requires_n_passed=1,
    target=None,
    mark_col="significant_example1",
)
filtered = stats_fully_pep.filter(pl.col("significant_example1"))
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (2228, 30)):

shape: (5, 30)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ c_cut_sit ┆ mapped_sp ┆ significa ┆ significa │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ e         ┆ ecies_fro ┆ nt        ┆ nt_exampl │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ m_peptide ┆ ---       ┆ e1        │
│ str       ┆ f64       ┆          ┆           ┆   ┆ str       ┆ ---       ┆ bool      ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆           ┆ bool      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -150.8905 ┆ … ┆ Q8WUW1-67 ┆ HUMAN     ┆ true      ┆ true      │
│           ┆ 2         ┆          ┆ 13        ┆   ┆ _68       ┆           ┆           ┆           │
│ AGAFEHLPS ┆ -13.48500 ┆ 6.742503 ┆ -145.8312 ┆ … ┆ Q13641-14 ┆ HUMAN     ┆ true      ┆ true      │
│ LR        ┆ 6         ┆          ┆ 44        ┆   ┆ 5_146     ┆           ┆           ┆           │
│ QMADTGKLN ┆ -13.45295 ┆ 6.72648  ┆ -145.6907 ┆ … ┆ Q00839-55 ┆ HUMAN     ┆ true      ┆ true      │
│ TLLQR     ┆ 9         ┆          ┆ 79        ┆   ┆ 8_559     ┆           ┆           ┆           │
│ LQDLQGEKD ┆ -13.04591 ┆ 6.522955 ┆ -140.9106 ┆ … ┆ O60610-52 ┆ HUMAN     ┆ true      ┆ true      │
│ ALHSEK    ┆           ┆          ┆ 85        ┆   ┆ 7_528     ┆           ┆           ┆           │
│ LTEELKEQM ┆ -12.95668 ┆ 6.478341 ┆ -135.4388 ┆ … ┆ Q14683-69 ┆ HUMAN     ┆ true      ┆ true      │
│ K         ┆ 2         ┆          ┆ 94        ┆   ┆ 0_691     ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Selecting Significant Detections (Experiment-Specific)

- This example dataset is specific compared to a typical experiment because we have prior knowledge that all human peptides exhibit a fold change of 1/2.5 in the pair `"H2_Y100_vs_H5_Y100"` or 6/1 in the pair `"H30_Y100_vs_H5_Y100"`.
- This example demonstrates how the `do_significant_selection` function handles more customized selection criteria.

In [28]:
stats_fully_pep = lipana.stats.do_significant_selection(
    stats_fully_pep,
    rules=[
        lipana.stats.SignificantRule(
            greater_than=None,
            less_than=(("adj_pvalue_group_wise", 0.05), ("log2_fc_limma", -np.log2(1.5))),
            gt_value_or_lt_negate=None,
            equal_to=None,
            expression_rule=None,  # this parameter allows you to define a custom polars expression to handle more complex conditions
            filter_condition=pl.col("pair").eq("H2_Y100_vs_H5_Y100"),
        ),
        lipana.stats.SignificantRule(
            greater_than=("log2_fc_limma", np.log2(1.5)),
            less_than=("adj_pvalue_group_wise", 0.05),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=pl.col("pair").eq("H30_Y100_vs_H5_Y100"),
        ),
    ],
    requires_n_passed=1,
    target=None,
    mark_col="significant_example2",
)
filtered = stats_fully_pep.filter(pl.col("significant_example2"))
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (2218, 31)):

shape: (5, 31)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ mapped_sp ┆ significa ┆ significa ┆ significa │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ ecies_fro ┆ nt        ┆ nt_exampl ┆ nt_exampl │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ m_peptide ┆ ---       ┆ e1        ┆ e2        │
│ str       ┆ f64       ┆          ┆           ┆   ┆ ---       ┆ bool      ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ str       ┆           ┆ bool      ┆ bool      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -150.8905 ┆ … ┆ HUMAN     ┆ true      ┆ true      ┆ true      │
│           ┆ 2         ┆          ┆ 13        ┆   ┆           ┆           ┆           ┆           │
│ AGAFEHLPS ┆ -13.48500 ┆ 6.742503 ┆ -145.8312 ┆ … ┆ HUMAN     ┆ true      ┆ true      ┆ true      │
│ LR        ┆ 6         ┆          ┆ 44        ┆   ┆           ┆           ┆           ┆           │
│ QMADTGKLN ┆ -13.45295 ┆ 6.72648  ┆ -145.6907 ┆ … ┆ HUMAN     ┆ true      ┆ true      ┆ true      │
│ TLLQR     ┆ 9         ┆          ┆ 79        ┆   ┆           ┆           ┆           ┆           │
│ LQDLQGEKD ┆ -13.04591 ┆ 6.522955 ┆ -140.9106 ┆ … ┆ HUMAN     ┆ true      ┆ true      ┆ true      │
│ ALHSEK    ┆           ┆          ┆ 85        ┆   ┆           ┆           ┆           ┆           │
│ LTEELKEQM ┆ -12.95668 ┆ 6.478341 ┆ -135.4388 ┆ … ┆ HUMAN     ┆ true      ┆ true      ┆ true      │
│ K         ┆ 2         ┆          ┆ 94        ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Example 2: Test on Semi-Specific Stripped Peptides and Aggregate to Cut Site Level

This example demonstrates a multi-step process:

1. Selects semi-specific peptides from search reports.
2. Performs hypothesis tests on these selected peptides.
3. Annotates the results with non-restricted cut sites.
4. Aggregates the peptide-level p-values and fold changes to the cut site level.

#### Performing Hypothesis Tests on Semi-Specific Stripped Peptides

- First, we select the semi-specific peptides from the complete search report, and then perform hypothesis tests on this subset.

In [29]:
design = lipana.ComparisonDesign(exp_layout, (("H2_Y100", "H5_Y100"), ("H30_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

filters = (pl.col("peptide_enzymatic_specificity") == "semi_specific") & (
    pl.col("mapped_species_from_peptide").is_in(("HUMAN", "YEAST"))
)

stats_semi_pep = lipana.stats.pipe.do_stats_pipe_direct(
    qdf=report.get_quant_data(
        entry_name="stripped_peptide",
        quant_name="peptide_quant_by_maxlfq_from_ms1ms2",
        main_df_entry_filter=filters,
    ),  # Note here no need to call `.df` because the requirement of filtering will make this function return a dataframe, instead of a `EntryQuantificationReport` object
    design=design,
    entry_level="stripped_peptide",
    mv_config=lipana.FullEmptyFillingMissingValueHandler(3),
    min_rep_count=3,
    annotation_df=report.df.filter(filters),
    group_entry_level="protein_group",  # Note this parameter is given because FDR control also can be done on the protein level
    annotation_cols=[
        "peptide_start_position",
        "peptide_end_position",
        "prev_aa",
        "next_aa",
        "peptide_n_term_aa",
        "peptide_c_term_aa",
        "nterm_enzymatic_specificity",
        "cterm_enzymatic_specificity",
        "peptide_enzymatic_specificity",
        "n_cut_site",
        "c_cut_site",
    ],
    return_chains=False,
)
sleep(0.1)
print(f"First 5 rows of the result (total size: {stats_semi_pep.shape}):")
stats_semi_pep.head(5)

design.pairwise_comparisons = (('H2_Y100', 'H5_Y100'), ('H30_Y100', 'H5_Y100'))

Quantification file: /tmp/tmpkmwf00zm.txt
All defined comparison pairs: c("H2_Y100", "H5_Y100")
Available comparison pairs: c("H2_Y100", "H5_Y100")
Comparing H2_Y100 vs H5_Y100
Output to /tmp/tmpkmwf00zm.txt-limma_output.txt
Quantification file: /tmp/tmpaho7ehmu.txt
All defined comparison pairs: c("H30_Y100", "H5_Y100")
Available comparison pairs: c("H30_Y100", "H5_Y100")
Comparing H30_Y100 vs H5_Y100
Output to /tmp/tmpaho7ehmu.txt-limma_output.txt

First 5 rows of the result (total size: (8930, 27)):

shape: (5, 27)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ cterm_enz ┆ peptide_e ┆ n_cut_sit ┆ c_cut_sit │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ ymatic_sp ┆ nzymatic_ ┆ e         ┆ e         │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ecificity ┆ specifici ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆          ┆           ┆   ┆ ---       ┆ ty        ┆ str       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆ str       ┆ ---       ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -140.8796 ┆ … ┆ non_restr ┆ semi_spec ┆ P08865-10 ┆ P08865-11 │
│ IQAA      ┆ 4         ┆          ┆ 56        ┆   ┆ icted     ┆ ific      ┆ 2_103     ┆ 5_116     │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -140.7601 ┆ … ┆ restricte ┆ semi_spec ┆ Q14152-67 ┆ Q14152-67 │
│           ┆ 2         ┆          ┆ 14        ┆   ┆ d         ┆ ific      ┆ 1_672     ┆ 9_680     │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -138.6330 ┆ … ┆ non_restr ┆ semi_spec ┆ P08865-12 ┆ P08865-13 │
│           ┆ 3         ┆          ┆ 16        ┆   ┆ icted     ┆ ific      ┆ 8_129     ┆ 7_138     │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -136.6004 ┆ … ┆ restricte ┆ semi_spec ┆ O75122-11 ┆ O75122-11 │
│ IK        ┆           ┆          ┆ 59        ┆   ┆ d         ┆ ific      ┆ 70_1171   ┆ 81_1182   │
│ QQNQDPEVF ┆ -14.07648 ┆ 7.03824  ┆ -131.4125 ┆ … ┆ restricte ┆ semi_spec ┆ Q9NPI6-46 ┆ Q9NPI6-47 │
│ VQPK      ┆ 1         ┆          ┆ 13        ┆   ┆ d         ┆ ific      ┆ 3_464     ┆ 6_477     │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Aggregating Test Results from Peptides to Cut Sites

- Here, we use the `"combine_p_direction_check"` pipeline as an example.

In [30]:
stats_cut_site_agg = lipana.stats.pipe.do_stats_pipe_agg(
    qdf=stats_semi_pep,
    base_entry="stripped_peptide",
    target_entry="cut_site",
    group_entry="protein_group",
    annotation_df=report.df.filter(~pl.col("cut_site_is_restricted")),
    annotation_cols=[
        "cut_site",
        "cut_site_n_aa",
        "cut_site_c_aa",
        "cut_site_on_term",
        "cut_site_is_restricted",
    ],
    pipeline="combine_p_direction_check",
)
print(f"First 5 rows of the result (total size: {stats_cut_site_agg.shape}):")
stats_cut_site_agg.head(5)

/home/lishsh/LiPAna_new_version/lipana/stats/infer.py:101: RuntimeWarning: All-NaN slice encountered
  func_out = func(x)

First 5 rows of the result (total size: (8998, 43)):

shape: (5, 43)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ pvalue_co ┆ first_non ┆ adj_pvalu ┆ adj_pvalu │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ mbined    ┆ nan_in_co ┆ e_combine ┆ e_combine │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ mbined    ┆ d_exp_wis ┆ d_group_w │
│ str       ┆ f64       ┆          ┆           ┆   ┆ f64       ┆ ---       ┆ e         ┆ ise       │
│           ┆           ┆          ┆           ┆   ┆           ┆ bool      ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -140.8796 ┆ … ┆ 4.0135e-1 ┆ true      ┆ 6.7281e-1 ┆ 1.3443e-1 │
│ IQAA      ┆ 4         ┆          ┆ 56        ┆   ┆ 3         ┆           ┆ 1         ┆ 2         │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -140.7601 ┆ … ┆ 4.0369e-1 ┆ true      ┆ 6.7281e-1 ┆ 2.8258e-1 │
│           ┆ 2         ┆          ┆ 14        ┆   ┆ 3         ┆           ┆ 1         ┆ 2         │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -138.6330 ┆ … ┆ 4.4808e-1 ┆ true      ┆ 6.7281e-1 ┆ 1.3443e-1 │
│           ┆ 3         ┆          ┆ 16        ┆   ┆ 3         ┆           ┆ 1         ┆ 2         │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -136.6004 ┆ … ┆ 4.9581e-1 ┆ true      ┆ 6.7281e-1 ┆ 4.9581e-1 │
│ IK        ┆           ┆          ┆ 59        ┆   ┆ 3         ┆           ┆ 1         ┆ 3         │
│ QQNQDPEVF ┆ -14.07648 ┆ 7.03824  ┆ -131.4125 ┆ … ┆ 6.4645e-1 ┆ true      ┆ 7.9749e-1 ┆ 1.9394e-1 │
│ VQPK      ┆ 1         ┆          ┆ 13        ┆   ┆ 3         ┆           ┆ 1         ┆ 2         │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Selecting Significant Cut Sites

- This example continues to use the specific rules for this dataset. The difference compared to selecting fully-specific peptides in Example 1 lies in the columns used: `"adj_pvalue_combined_group_wise"` and `"log2_fc_limma_combined"`. These two columns are generated specifically by the `"combine_p"` aggregation pipeline.
- Note: To retain peptide-level information, you might observe duplicated rows for some cut sites within each pair, as a single cut site can originate from multiple peptides. The statistical results will be identical for each instance of a cut site within a pair. You can simply select unique entries based on the combination of `("cut_site", "pair")` columns if the peptide-level information is not required.

In [31]:
stats_cut_site_agg = lipana.stats.do_significant_selection(
    stats_cut_site_agg,
    rules=[
        lipana.stats.SignificantRule(
            greater_than=None,
            less_than=(("adj_pvalue_combined_group_wise", 0.05), ("log2_fc_limma_combined", -np.log2(1.5))),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=pl.col("pair").eq("H2_Y100_vs_H5_Y100"),
        ),
        lipana.stats.SignificantRule(
            greater_than=("log2_fc_limma_combined", np.log2(1.5)),
            less_than=("adj_pvalue_combined_group_wise", 0.05),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=pl.col("pair").eq("H30_Y100_vs_H5_Y100"),
        ),
    ],
    requires_n_passed=1,
    target=None,
    mark_col="significant",
)
filtered = stats_cut_site_agg.filter(pl.col("significant"))
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (1277, 44)):

shape: (5, 44)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ first_non ┆ adj_pvalu ┆ adj_pvalu ┆ significa │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ nan_in_co ┆ e_combine ┆ e_combine ┆ nt        │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ mbined    ┆ d_exp_wis ┆ d_group_w ┆ ---       │
│ str       ┆ f64       ┆          ┆           ┆   ┆ ---       ┆ e         ┆ ise       ┆ bool      │
│           ┆           ┆          ┆           ┆   ┆ bool      ┆ ---       ┆ ---       ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆ f64       ┆ f64       ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -140.8796 ┆ … ┆ true      ┆ 6.7281e-1 ┆ 1.3443e-1 ┆ true      │
│ IQAA      ┆ 4         ┆          ┆ 56        ┆   ┆           ┆ 1         ┆ 2         ┆           │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -140.7601 ┆ … ┆ true      ┆ 6.7281e-1 ┆ 2.8258e-1 ┆ true      │
│           ┆ 2         ┆          ┆ 14        ┆   ┆           ┆ 1         ┆ 2         ┆           │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -138.6330 ┆ … ┆ true      ┆ 6.7281e-1 ┆ 1.3443e-1 ┆ true      │
│           ┆ 3         ┆          ┆ 16        ┆   ┆           ┆ 1         ┆ 2         ┆           │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -136.6004 ┆ … ┆ true      ┆ 6.7281e-1 ┆ 4.9581e-1 ┆ true      │
│ IK        ┆           ┆          ┆ 59        ┆   ┆           ┆ 1         ┆ 3         ┆           │
│ QQNQDPEVF ┆ -14.07648 ┆ 7.03824  ┆ -131.4125 ┆ … ┆ true      ┆ 7.9749e-1 ┆ 1.9394e-1 ┆ true      │
│ VQPK      ┆ 1         ┆          ┆ 13        ┆   ┆           ┆ 1         ┆ 2         ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Example 3: Test on Cut Site Level Directly

This example demonstrates a single-step process for performing tests directly at the cut site level, using the cut-site-level quantification matrix generated previously.

#### Performing Hypothesis Tests on Cut Sites

- Hypothesis tests are performed directly on the pre-aggregated cut-site-level quantification data.
- You will notice that the `annotation_cols` parameter might have commented-out entries corresponding to columns used in Example 2. These columns are excluded here because they relate to the peptide origin of each cut site (peptide-related information) and could lead to duplicate rows (e.g., a cut site might originate from the N-terminus of one peptide and the C-terminus of another).

In [32]:
design = lipana.ComparisonDesign(exp_layout, (("H2_Y100", "H5_Y100"), ("H30_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

filters = (
    (pl.col("peptide_enzymatic_specificity") == "semi_specific")
    & (~pl.col("cut_site_is_restricted"))
    & (pl.col("mapped_species_from_peptide").is_in(("HUMAN", "YEAST")))
)

stats_cut_site_direct = lipana.stats.pipe.do_stats_pipe_direct(
    qdf=report.get_quant_data(
        entry_name="cut_site",
        quant_name="nonrestricted_cut_site_by_maxlfq_from_prec",
        main_df_entry_filter=filters,
    ),
    design=design,
    entry_level="cut_site",
    mv_config=lipana.FullEmptyFillingMissingValueHandler(3),
    min_rep_count=3,
    annotation_df=report.df.filter(filters),
    group_entry_level="protein_group",
    annotation_cols=[
        "mapped_species_from_peptide",
        # "cut_site_n_aa",
        # "cut_site_c_aa",
        # "cut_site_on_term",
        "cut_site_is_restricted",
    ],
    return_chains=False,
)
sleep(0.1)
print(f"First 5 rows of the result (total size: {stats_cut_site_direct.shape}):")
stats_cut_site_direct.head(5)

design.pairwise_comparisons = (('H2_Y100', 'H5_Y100'), ('H30_Y100', 'H5_Y100'))

Quantification file: /tmp/tmpren643sr.txt
All defined comparison pairs: c("H2_Y100", "H5_Y100")
Available comparison pairs: c("H2_Y100", "H5_Y100")
Comparing H2_Y100 vs H5_Y100
Output to /tmp/tmpren643sr.txt-limma_output.txt
Quantification file: /tmp/tmpxd02gea1.txt
All defined comparison pairs: c("H30_Y100", "H5_Y100")
Available comparison pairs: c("H30_Y100", "H5_Y100")
Comparing H30_Y100 vs H5_Y100
Output to /tmp/tmpxd02gea1.txt-limma_output.txt

First 5 rows of the result (total size: (8204, 18)):

shape: (5, 18)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cut_site  ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ protein_g ┆ adj_pvalu ┆ mapped_sp ┆ cut_site_ │
│ ---       ┆ imma      ┆ ---      ┆ ---       ┆   ┆ roup      ┆ e_group_w ┆ ecies_fro ┆ is_restri │
│ str       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ ise       ┆ m_peptide ┆ cted      │
│           ┆ f64       ┆          ┆           ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆ f64       ┆ str       ┆ bool      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ P08865-11 ┆ -15.04351 ┆ 7.521757 ┆ -143.7594 ┆ … ┆ P08865    ┆ 2.2320e-1 ┆ HUMAN     ┆ false     │
│ 5_116     ┆ 4         ┆          ┆           ┆   ┆           ┆ 2         ┆           ┆           │
│ Q14152-67 ┆ -15.25908 ┆ 7.629541 ┆ -143.5435 ┆ … ┆ Q14152    ┆ 3.0102e-1 ┆ HUMAN     ┆ false     │
│ 1_672     ┆ 2         ┆          ┆ 94        ┆   ┆           ┆ 2         ┆           ┆           │
│ O75122-11 ┆ -14.37804 ┆ 7.18902  ┆ -139.4824 ┆ … ┆ O75122    ┆ 4.5782e-1 ┆ HUMAN     ┆ false     │
│ 70_1171   ┆           ┆          ┆ 63        ┆   ┆           ┆ 3         ┆           ┆           │
│ Q9NPI6-46 ┆ -14.07648 ┆ 7.03824  ┆ -134.0803 ┆ … ┆ Q9NPI6    ┆ 1.7991e-1 ┆ HUMAN     ┆ false     │
│ 3_464     ┆ 1         ┆          ┆ 62        ┆   ┆           ┆ 2         ┆           ┆           │
│ O43809-27 ┆ -14.14661 ┆ 7.073305 ┆ -132.0693 ┆ … ┆ O43809    ┆ 6.6495e-1 ┆ HUMAN     ┆ false     │
│ _28       ┆ 1         ┆          ┆ 92        ┆   ┆           ┆ 3         ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Selecting Significant Cut Sites

- This example performs the selection of significant detections based on the direct test results, similar to Example 1. It does not require modifying the columns used for significance criteria, unlike the aggregation approach in Example 2.

In [33]:
stats_cut_site_direct = lipana.stats.do_significant_selection(
    stats_cut_site_direct,
    rules=[
        lipana.stats.SignificantRule(
            greater_than=None,
            less_than=(("adj_pvalue_group_wise", 0.05), ("log2_fc_limma", -np.log2(1.5))),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=pl.col("pair").eq("H2_Y100_vs_H5_Y100"),
        ),
        lipana.stats.SignificantRule(
            greater_than=("log2_fc_limma", np.log2(1.5)),
            less_than=("adj_pvalue_group_wise", 0.05),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=pl.col("pair").eq("H30_Y100_vs_H5_Y100"),
        ),
    ],
    requires_n_passed=1,
    target=None,
    mark_col="significant",
)
filtered = stats_cut_site_direct.filter(pl.col("significant"))
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (1243, 19)):

shape: (5, 19)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cut_site  ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ adj_pvalu ┆ mapped_sp ┆ cut_site_ ┆ significa │
│ ---       ┆ imma      ┆ ---      ┆ ---       ┆   ┆ e_group_w ┆ ecies_fro ┆ is_restri ┆ nt        │
│ str       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ise       ┆ m_peptide ┆ cted      ┆ ---       │
│           ┆ f64       ┆          ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ bool      │
│           ┆           ┆          ┆           ┆   ┆ f64       ┆ str       ┆ bool      ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ P08865-11 ┆ -15.04351 ┆ 7.521757 ┆ -143.7594 ┆ … ┆ 2.2320e-1 ┆ HUMAN     ┆ false     ┆ true      │
│ 5_116     ┆ 4         ┆          ┆           ┆   ┆ 2         ┆           ┆           ┆           │
│ Q14152-67 ┆ -15.25908 ┆ 7.629541 ┆ -143.5435 ┆ … ┆ 3.0102e-1 ┆ HUMAN     ┆ false     ┆ true      │
│ 1_672     ┆ 2         ┆          ┆ 94        ┆   ┆ 2         ┆           ┆           ┆           │
│ O75122-11 ┆ -14.37804 ┆ 7.18902  ┆ -139.4824 ┆ … ┆ 4.5782e-1 ┆ HUMAN     ┆ false     ┆ true      │
│ 70_1171   ┆           ┆          ┆ 63        ┆   ┆ 3         ┆           ┆           ┆           │
│ Q9NPI6-46 ┆ -14.07648 ┆ 7.03824  ┆ -134.0803 ┆ … ┆ 1.7991e-1 ┆ HUMAN     ┆ false     ┆ true      │
│ 3_464     ┆ 1         ┆          ┆ 62        ┆   ┆ 2         ┆           ┆           ┆           │
│ O43809-27 ┆ -14.14661 ┆ 7.073305 ┆ -132.0693 ┆ … ┆ 6.6495e-1 ┆ HUMAN     ┆ false     ┆ true      │
│ _28       ┆ 1         ┆          ┆ 92        ┆   ┆ 3         ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Example 4: Test on All Stripped Peptides and Aggregate to Protein Group Level

This example performs hypothesis tests on all stripped peptides (regardless of specificity) and then aggregates the results to the protein group level. The aggregation method used here selects the base peptide(s) with the minimum p-value(s) for each protein group (e.g., using `"sel_min_p"` or `"sel_min2_p"`).

#### Performing Hypothesis Tests on All Peptides

In [34]:
design = lipana.ComparisonDesign(exp_layout, (("H2_Y100", "H5_Y100"), ("H30_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

filters = pl.col("mapped_species_from_peptide").is_in(("HUMAN", "YEAST"))

stats_all_pep = lipana.stats.pipe.do_stats_pipe_direct(
    qdf=report.get_quant_data(
        entry_name="stripped_peptide",
        quant_name="peptide_quant_by_maxlfq_from_ms1ms2",
        main_df_entry_filter=filters,
    ),  # Note here no need to call `.df` because the requirement of filtering will make this function return a dataframe, instead of a `EntryQuantificationReport` object
    design=design,
    entry_level="stripped_peptide",
    mv_config=lipana.FullEmptyFillingMissingValueHandler(3),
    min_rep_count=3,
    annotation_df=report.df.filter(filters),
    group_entry_level="protein_group",  # Note this parameter is given because FDR control also can be done on the protein level
    annotation_cols=[
        "peptide_start_position",
        "peptide_end_position",
        "prev_aa",
        "next_aa",
        "peptide_n_term_aa",
        "peptide_c_term_aa",
        "nterm_enzymatic_specificity",
        "cterm_enzymatic_specificity",
        "peptide_enzymatic_specificity",
        "n_cut_site",
        "c_cut_site",
    ],
    return_chains=False,
)
sleep(0.1)
print(f"First 5 rows of the result (total size: {stats_all_pep.shape}):")
stats_all_pep.head(5)

design.pairwise_comparisons = (('H2_Y100', 'H5_Y100'), ('H30_Y100', 'H5_Y100'))

Quantification file: /tmp/tmp_sxercf6.txt
All defined comparison pairs: c("H2_Y100", "H5_Y100")
Available comparison pairs: c("H2_Y100", "H5_Y100")
Comparing H2_Y100 vs H5_Y100
Output to /tmp/tmp_sxercf6.txt-limma_output.txt
Quantification file: /tmp/tmpj4g36a2n.txt
All defined comparison pairs: c("H30_Y100", "H5_Y100")
Available comparison pairs: c("H30_Y100", "H5_Y100")
Comparing H30_Y100 vs H5_Y100
Output to /tmp/tmpj4g36a2n.txt-limma_output.txt

First 5 rows of the result (total size: (19056, 27)):

shape: (5, 27)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ cterm_enz ┆ peptide_e ┆ n_cut_sit ┆ c_cut_sit │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ ymatic_sp ┆ nzymatic_ ┆ e         ┆ e         │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ecificity ┆ specifici ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆          ┆           ┆   ┆ ---       ┆ ty        ┆ str       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆ str       ┆ ---       ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -150.9483 ┆ … ┆ non_restr ┆ semi_spec ┆ P08865-10 ┆ P08865-11 │
│ IQAA      ┆ 4         ┆          ┆ 64        ┆   ┆ icted     ┆ ific      ┆ 2_103     ┆ 5_116     │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -150.3989 ┆ … ┆ restricte ┆ semi_spec ┆ Q14152-67 ┆ Q14152-67 │
│           ┆ 2         ┆          ┆ 87        ┆   ┆ d         ┆ ific      ┆ 1_672     ┆ 9_680     │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -149.2207 ┆ … ┆ non_restr ┆ semi_spec ┆ P08865-12 ┆ P08865-13 │
│           ┆ 3         ┆          ┆ 3         ┆   ┆ icted     ┆ ific      ┆ 8_129     ┆ 7_138     │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -146.7688 ┆ … ┆ restricte ┆ semi_spec ┆ O75122-11 ┆ O75122-11 │
│ IK        ┆           ┆          ┆ 5         ┆   ┆ d         ┆ ific      ┆ 70_1171   ┆ 81_1182   │
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -142.3270 ┆ … ┆ restricte ┆ fully_spe ┆ Q8WUW1-59 ┆ Q8WUW1-67 │
│           ┆ 2         ┆          ┆ 75        ┆   ┆ d         ┆ cific     ┆ _60       ┆ _68       │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Selecting Significant Protein Groups Based on the Minimum P-value Peptide

- Note: In this pipeline, a `top_k_selected` column is added to the results. This column indicates whether a peptide is among the top *k* peptides with the lowest p-values within its group (here, *k*=1). In the `do_significant_selection` function, an additional condition `pl.col("top_k_selected")` is added to the `filter_condition` parameter. This ensures that the significance selection is based only on the single peptide with the minimum p-value within each protein group.

In [35]:
stats_protein_group_agg_pep_minp = lipana.stats.pipe.do_stats_pipe_agg(
    qdf=stats_all_pep,
    base_entry="stripped_peptide",
    target_entry="protein_group",
    group_entry=None,
    annotation_df=None,
    annotation_cols=None,
    pipeline="sel_min_p",
)
print(f"First 5 rows of the result (total size: {stats_protein_group_agg_pep_minp.shape}):")
stats_protein_group_agg_pep_minp.head(5)

First 5 rows of the result (total size: (19056, 28)):

shape: (5, 28)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ peptide_e ┆ n_cut_sit ┆ c_cut_sit ┆ top_k_sel │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ nzymatic_ ┆ e         ┆ e         ┆ ected     │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ specifici ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆          ┆           ┆   ┆ ty        ┆ str       ┆ str       ┆ bool      │
│           ┆           ┆          ┆           ┆   ┆ ---       ┆           ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -150.9483 ┆ … ┆ semi_spec ┆ P08865-10 ┆ P08865-11 ┆ true      │
│ IQAA      ┆ 4         ┆          ┆ 64        ┆   ┆ ific      ┆ 2_103     ┆ 5_116     ┆           │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -150.3989 ┆ … ┆ semi_spec ┆ Q14152-67 ┆ Q14152-67 ┆ true      │
│           ┆ 2         ┆          ┆ 87        ┆   ┆ ific      ┆ 1_672     ┆ 9_680     ┆           │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -149.2207 ┆ … ┆ semi_spec ┆ P08865-12 ┆ P08865-13 ┆ false     │
│           ┆ 3         ┆          ┆ 3         ┆   ┆ ific      ┆ 8_129     ┆ 7_138     ┆           │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -146.7688 ┆ … ┆ semi_spec ┆ O75122-11 ┆ O75122-11 ┆ true      │
│ IK        ┆           ┆          ┆ 5         ┆   ┆ ific      ┆ 70_1171   ┆ 81_1182   ┆           │
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -142.3270 ┆ … ┆ fully_spe ┆ Q8WUW1-59 ┆ Q8WUW1-67 ┆ true      │
│           ┆ 2         ┆          ┆ 75        ┆   ┆ cific     ┆ _60       ┆ _68       ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [36]:
stats_protein_group_agg_pep_minp = lipana.stats.do_significant_selection(
    stats_protein_group_agg_pep_minp,
    rules=[
        lipana.stats.SignificantRule(
            greater_than=None,
            less_than=(("adj_pvalue_group_wise", 0.05), ("log2_fc_limma", -np.log2(1.5))),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=(pl.col("pair").eq("H2_Y100_vs_H5_Y100") & pl.col("top_k_selected")),
        ),
        lipana.stats.SignificantRule(
            greater_than=("log2_fc_limma", np.log2(1.5)),
            less_than=("adj_pvalue_group_wise", 0.05),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=(pl.col("pair").eq("H30_Y100_vs_H5_Y100") & pl.col("top_k_selected")),
        ),
    ],
    requires_n_passed=1,
    target=None,
    mark_col="significant",
)
filtered = stats_protein_group_agg_pep_minp.filter(pl.col("significant"))
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (788, 29)):

shape: (5, 29)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ n_cut_sit ┆ c_cut_sit ┆ top_k_sel ┆ significa │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ e         ┆ e         ┆ ected     ┆ nt        │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆          ┆           ┆   ┆ str       ┆ str       ┆ bool      ┆ bool      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -150.9483 ┆ … ┆ P08865-10 ┆ P08865-11 ┆ true      ┆ true      │
│ IQAA      ┆ 4         ┆          ┆ 64        ┆   ┆ 2_103     ┆ 5_116     ┆           ┆           │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -150.3989 ┆ … ┆ Q14152-67 ┆ Q14152-67 ┆ true      ┆ true      │
│           ┆ 2         ┆          ┆ 87        ┆   ┆ 1_672     ┆ 9_680     ┆           ┆           │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -146.7688 ┆ … ┆ O75122-11 ┆ O75122-11 ┆ true      ┆ true      │
│ IK        ┆           ┆          ┆ 5         ┆   ┆ 70_1171   ┆ 81_1182   ┆           ┆           │
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -142.3270 ┆ … ┆ Q8WUW1-59 ┆ Q8WUW1-67 ┆ true      ┆ true      │
│           ┆ 2         ┆          ┆ 75        ┆   ┆ _60       ┆ _68       ┆           ┆           │
│ QQNQDPEVF ┆ -14.07648 ┆ 7.03824  ┆ -140.7218 ┆ … ┆ Q9NPI6-46 ┆ Q9NPI6-47 ┆ true      ┆ true      │
│ VQPK      ┆ 1         ┆          ┆ 78        ┆   ┆ 3_464     ┆ 6_477     ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Selecting Significant Protein Groups Based on the Top 2 Lowest P-value Peptides

- The primary output here, `stats_protein_group_agg_pep_minp2`, will be nearly identical to the previous output (`stats_protein_group_agg_pep_minp`), except for the values in the `top_k_selected` column. This column will now contain `True` if the peptide is one of the two peptides with the lowest p-values within its protein group.
- The command for selecting significant detections includes the following changes:
  - `requires_n_passed=2`
  - `target="protein_group"`
- After the selection annotation step, in addition to the `significant` column (indicating if an individual peptide meets the significance rule), a `significant_2passed` column will be added. This column annotates whether the protein group has a sufficient number (2 in this case) of significant peptides among the top 2 selected. If you set *k* to 3, this column would be named `significant_3passed`.
- Note: In this scenario, the `rules` parameter for the `do_significant_selection` function should include rules defined with an additional filter condition involving `pl.col("top_k_selected")`. For example: `filter_condition=(pl.col("pair").eq("H30_Y100_vs_H5_Y100") & pl.col("top_k_selected"))`. This setup ensures that we specifically check if the *two peptides with the lowest p-values* are significant, rather than checking if *any* two peptides within the protein group pass the significance criteria.

In [37]:
stats_protein_group_agg_pep_minp2 = lipana.stats.pipe.do_stats_pipe_agg(
    qdf=stats_all_pep,
    base_entry="stripped_peptide",
    target_entry="protein_group",
    group_entry=None,
    annotation_df=None,
    annotation_cols=None,
    pipeline="sel_min2_p",
)
print(f"First 5 rows of the result (total size: {stats_protein_group_agg_pep_minp2.shape}):")
stats_protein_group_agg_pep_minp2.head(5)

First 5 rows of the result (total size: (19056, 28)):

shape: (5, 28)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ peptide_e ┆ n_cut_sit ┆ c_cut_sit ┆ top_k_sel │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ nzymatic_ ┆ e         ┆ e         ┆ ected     │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ specifici ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆          ┆           ┆   ┆ ty        ┆ str       ┆ str       ┆ bool      │
│           ┆           ┆          ┆           ┆   ┆ ---       ┆           ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -150.9483 ┆ … ┆ semi_spec ┆ P08865-10 ┆ P08865-11 ┆ true      │
│ IQAA      ┆ 4         ┆          ┆ 64        ┆   ┆ ific      ┆ 2_103     ┆ 5_116     ┆           │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -150.3989 ┆ … ┆ semi_spec ┆ Q14152-67 ┆ Q14152-67 ┆ true      │
│           ┆ 2         ┆          ┆ 87        ┆   ┆ ific      ┆ 1_672     ┆ 9_680     ┆           │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -149.2207 ┆ … ┆ semi_spec ┆ P08865-12 ┆ P08865-13 ┆ true      │
│           ┆ 3         ┆          ┆ 3         ┆   ┆ ific      ┆ 8_129     ┆ 7_138     ┆           │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -146.7688 ┆ … ┆ semi_spec ┆ O75122-11 ┆ O75122-11 ┆ true      │
│ IK        ┆           ┆          ┆ 5         ┆   ┆ ific      ┆ 70_1171   ┆ 81_1182   ┆           │
│ RIEYIEAR  ┆ -14.26971 ┆ 7.134856 ┆ -142.3270 ┆ … ┆ fully_spe ┆ Q8WUW1-59 ┆ Q8WUW1-67 ┆ true      │
│           ┆ 2         ┆          ┆ 75        ┆   ┆ cific     ┆ _60       ┆ _68       ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [38]:
stats_protein_group_agg_pep_minp2 = lipana.stats.do_significant_selection(
    stats_protein_group_agg_pep_minp2,
    rules=[
        lipana.stats.SignificantRule(
            greater_than=None,
            less_than=(("adj_pvalue_exp_wise", 0.05), ("log2_fc_limma", -np.log2(1.5))),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=(pl.col("pair").eq("H2_Y100_vs_H5_Y100") & pl.col("top_k_selected")),
        ),
        lipana.stats.SignificantRule(
            greater_than=("log2_fc_limma", np.log2(1.5)),
            less_than=("adj_pvalue_exp_wise", 0.05),
            gt_value_or_lt_negate=None,
            equal_to=None,
            filter_condition=(pl.col("pair").eq("H30_Y100_vs_H5_Y100") & pl.col("top_k_selected")),
        ),
    ],
    requires_n_passed=2,  # Note here the number of passed rules is required to be 2, which just matches the number of selected top k (minimum p-value) peptides in column `top_k_selected`
    target=(
        "protein_group",
        "pair",
    ),  # Note here the target should be given to concretely specify from where to ensure two peptides are significant
    mark_col="significant",
)
filtered = stats_protein_group_agg_pep_minp2.filter(
    pl.col("significant_2passed")
)  # Note here the selection is based on `significant_2passed` column
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (8391, 30)):

shape: (5, 30)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ c_cut_sit ┆ top_k_sel ┆ significa ┆ significa │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ e         ┆ ected     ┆ nt        ┆ nt_2passe │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ d         │
│ str       ┆ f64       ┆          ┆           ┆   ┆ str       ┆ bool      ┆ bool      ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ bool      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -150.9483 ┆ … ┆ P08865-11 ┆ true      ┆ true      ┆ true      │
│ IQAA      ┆ 4         ┆          ┆ 64        ┆   ┆ 5_116     ┆           ┆           ┆           │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -150.3989 ┆ … ┆ Q14152-67 ┆ true      ┆ true      ┆ true      │
│           ┆ 2         ┆          ┆ 87        ┆   ┆ 9_680     ┆           ┆           ┆           │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -149.2207 ┆ … ┆ P08865-13 ┆ true      ┆ true      ┆ true      │
│           ┆ 3         ┆          ┆ 3         ┆   ┆ 7_138     ┆           ┆           ┆           │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -146.7688 ┆ … ┆ O75122-11 ┆ true      ┆ true      ┆ true      │
│ IK        ┆           ┆          ┆ 5         ┆   ┆ 81_1182   ┆           ┆           ┆           │
│ QQNQDPEVF ┆ -14.07648 ┆ 7.03824  ┆ -140.7218 ┆ … ┆ Q9NPI6-47 ┆ true      ┆ true      ┆ true      │
│ VQPK      ┆ 1         ┆          ┆ 78        ┆   ┆ 6_477     ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

- Note: in this case, after filtering the results by column "significant_2passed", you will always see all peptides of the selected significant protein groups. If you want to only see those peptides that are selected to support the protein groups that are significant, should add an additional condition to ensure column "significant" is true. That is, the filtered dataframe will have 2n rows to present 2n significant "peptide"+"comparison_pair", in which there are n selected significant "protein"+"comparison_pair"

In [39]:
filtered = stats_protein_group_agg_pep_minp2.filter(pl.col("significant_2passed") & pl.col("significant"))
print(f"First 5 rows of the result (total size: {filtered.shape}):")
filtered.head(5)

First 5 rows of the result (total size: (976, 30)):

shape: (5, 30)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ c_cut_sit ┆ top_k_sel ┆ significa ┆ significa │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ e         ┆ ected     ┆ nt        ┆ nt_2passe │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ d         │
│ str       ┆ f64       ┆          ┆           ┆   ┆ str       ┆ bool      ┆ bool      ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ bool      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FTPGTFTNQ ┆ -15.04351 ┆ 7.521757 ┆ -150.9483 ┆ … ┆ P08865-11 ┆ true      ┆ true      ┆ true      │
│ IQAA      ┆ 4         ┆          ┆ 64        ┆   ┆ 5_116     ┆           ┆           ┆           │
│ KQVEQLEK  ┆ -15.25908 ┆ 7.629541 ┆ -150.3989 ┆ … ┆ Q14152-67 ┆ true      ┆ true      ┆ true      │
│           ┆ 2         ┆          ┆ 87        ┆   ┆ 9_680     ┆           ┆           ┆           │
│ ADHQPLTEA ┆ -14.45983 ┆ 7.229916 ┆ -149.2207 ┆ … ┆ P08865-13 ┆ true      ┆ true      ┆ true      │
│           ┆ 3         ┆          ┆ 3         ┆   ┆ 7_138     ┆           ┆           ┆           │
│ ATSISPEQC ┆ -14.37804 ┆ 7.18902  ┆ -146.7688 ┆ … ┆ O75122-11 ┆ true      ┆ true      ┆ true      │
│ IK        ┆           ┆          ┆ 5         ┆   ┆ 81_1182   ┆           ┆           ┆           │
│ QQNQDPEVF ┆ -14.07648 ┆ 7.03824  ┆ -140.7218 ┆ … ┆ Q9NPI6-47 ┆ true      ┆ true      ┆ true      │
│ VQPK      ┆ 1         ┆          ┆ 78        ┆   ┆ 6_477     ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Utilities

### Retrieve annotation from main report for quantification data or statistic result

- To reduce the additional use of memory, all annotations are generally only stored in the report
- To retrieve these information from the main report, the table join can be done on the dataframe that needs some information and the main report `report.df`
- To handle some potential complicated cases, there is also a function `lipana.attach_annotation_from_other_df` to do this action
- Note: It is highly recommended to attach the desired annotations to the quantification dataframe and thoroughly verify their accuracy before proceeding with statistical analysis. This verification step is crucial because annotations can sometimes exhibit one-to-many (1:n) mappings. For example, reports from analysis software might list the same peptide sequence on multiple rows, associating it with different protein groups or genes in each instance.

In [40]:
# Retrieve some protein annotations for the stats result
stats_protein_group_agg_pep_minp = lipana.attach_annotation_from_other_df(
    df=stats_protein_group_agg_pep_minp,
    other_df=report.df,
    annotation_cols=[
        "Protein.Names",
        "Genes",
        "First.Protein.Description",
    ],
    on="protein_group",
    pre_filter=None,
    unique_on_key_only=False,
    method="leftjoin",
)
stats_protein_group_agg_pep_minp.sort("protein_group").unique("protein_group").head(5)

shape: (5, 32)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ stripped_p ┆ log2_fc_l ┆ AveExpr   ┆ t         ┆ … ┆ significa ┆ Protein.N ┆ Genes   ┆ First.Pro │
│ eptide     ┆ imma      ┆ ---       ┆ ---       ┆   ┆ nt        ┆ ames      ┆ ---     ┆ tein.Desc │
│ ---        ┆ ---       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ str     ┆ ription   │
│ str        ┆ f64       ┆           ┆           ┆   ┆ bool      ┆ str       ┆         ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ AVTEQGAELS ┆ -1.265568 ┆ 14.462931 ┆ -10.83860 ┆ … ┆ true      ┆ 1433T_HUM ┆ YWHAQ   ┆ 14-3-3    │
│ NEER       ┆           ┆           ┆ 3         ┆   ┆           ┆ AN        ┆         ┆ protein   │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ theta     │
│ DDVDDFQPR  ┆ null      ┆ null      ┆ null      ┆ … ┆ false     ┆ YO352_YEA ┆ YOR352W ┆ Uncharact │
│            ┆           ┆           ┆           ┆   ┆           ┆ ST        ┆         ┆ erized    │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ protein   │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ YOR352…   │
│ CVSSPHFQVA ┆ -12.84521 ┆ 6.422607  ┆ -94.44050 ┆ … ┆ true      ┆ 2A5D_HUMA ┆ PPP2R5D ┆ Serine/th │
│ ER         ┆ 4         ┆           ┆ 6         ┆   ┆           ┆ N         ┆         ┆ reonine-p │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ rotein    │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ phosp…    │
│ EEEEEEEQKI ┆ null      ┆ null      ┆ null      ┆ … ┆ false     ┆ XPA_HUMAN ┆ XPA     ┆ DNA       │
│ GK         ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ repair    │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ protein   │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ complemen │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ ti…       │
│ GSSSYSQLLA ┆ null      ┆ null      ┆ null      ┆ … ┆ false     ┆ XPO7_HUMA ┆ XPO7    ┆ Exportin- │
│ ATCLTK     ┆           ┆           ┆           ┆   ┆           ┆ N         ┆         ┆ 7         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘