# Load

In [ ]:
from pathlib import Path
import functools
import sys

import numpy as np
import polars as pl

sys.path.append(str(Path(".").resolve().parent))

import lipana

In [13]:
workspace = Path("./temp_data").absolute()

In [ ]:
exp_setting = lipana.ExperimentLayout.from_file("./temp_data/experiment_info.txt")
exp_setting.exp_df

shape: (20, 3)
┌─────────────────────────────────┬───────────┬───────────┐
│ run                             ┆ condition ┆ replicate │
│ ---                             ┆ ---       ┆ ---       │
│ str                             ┆ str       ┆ i64       │
╞═════════════════════════════════╪═══════════╪═══════════╡
│ 20240331_YSJ-HY_0_100-400ng_A_… ┆ H0_Y100   ┆ 1         │
│ 20240331_YSJ-HY_0_100-400ng_B_… ┆ H0_Y100   ┆ 2         │
│ 20240404_YSJ-HY_0_100-400ng_C_… ┆ H0_Y100   ┆ 3         │
│ 20240404_YSJ-HY_0_100-400ng_D_… ┆ H0_Y100   ┆ 4         │
│ 20240331_YSJ-HY_2d5_100-400ng_… ┆ H2d5_Y100 ┆ 1         │
│ …                               ┆ …         ┆ …         │
│ 20240404_YSJ-HY_7d5_100-400ng_… ┆ H7d5_Y100 ┆ 4         │
│ 20240331_YSJ-HY_25_100-400ng_A… ┆ H25_Y100  ┆ 1         │
│ 20240331_YSJ-HY_25_100-400ng_B… ┆ H25_Y100  ┆ 2         │
│ 20240404_YSJ-HY_25_100-400ng_C… ┆ H25_Y100  ┆ 3         │
│ 20240404_YSJ-HY_25_100-400ng_D… ┆ H25_Y100  ┆ 4         │
└─────────────────────────────────┴───────────┴───────────┘

In [14]:
parsed_fasta = lipana.parse_fasta(
    "./temp_data/FASTA-Merged_HomoScereIRTContam-Review_9606-Reviewed_559292-iRT11_Sep-CRAP_Type12-20241029.fasta",
    workspace=workspace,
    resume=True,
    write_parsed_fasta=True,
)

In [ ]:
path = Path("./temp_data/diann_report.tsv").absolute()
path

PosixPath('/home/data/LiPAna/example/temp_data/diann_report.tsv')

In [ ]:
report = lipana.DIANNReport.load_search_report(
    path,
    exp_setting=exp_setting,
    parsed_fasta=parsed_fasta,
    do_species_annotation=False,
)

# Quant

## Site quant

In [25]:
quant_data = report.construct_and_attach_quant_data(
    quant_name=None,
    method="maxlfq",
    filter_condition=True,
    run_col="run",
    primary_entry_col="cut_site",
    low_level_entry_col="precursor",
    base_quant_col="precursor_quantity_ms2",
    require_expansion=False,
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

MaxLFQ estimation via iq for /tmp/tmps3cfr7kk.txt

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmps3cfr7kk.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...
20 samples read

# lines read (excluding headers)      = 2441325
# quantitative values after filtering = 2441325

# samples  = 20
# proteins = 132379

Removing low intensities...

nrow = 2441325, # proteins = 132379, # samples = 20
Using 95 threads...
0%
5%
10%
15%
20%
25%
30%
35%
40%
45%
50%
55%
60%
65%
70%
75%
80%
86%
91%
96%
Completed.

Output to /tmp/tmps3cfr7kk.txt-iq_output.txt

In [33]:
quant_data._main_report = report

## Site quant df

In [28]:
report.list_quant_data_names("cut_site")

[('cut_site', 'maxlfq-precursor_quantity_ms2')]

In [47]:
site_qdf = report.get_quant_data(
    "cut_site",
    "maxlfq-precursor_quantity_ms2",
    main_df_entry_filter=(~pl.col("cut_site_is_restricted")),
)
site_qdf

shape: (34_889, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cut_site  ┆ 20240404_ ┆ 20240331_ ┆ 20240404_ ┆ … ┆ 20240331_ ┆ 20240331_ ┆ 20240404_ ┆ 20240404 │
│ ---       ┆ YSJ-HY_25 ┆ YSJ-HY_7d ┆ YSJ-HY_7d ┆   ┆ YSJ-HY_5_ ┆ YSJ-HY_2d ┆ YSJ-HY_5_ ┆ _YSJ-HY_ │
│ str       ┆ _100-400n ┆ 5_100-400 ┆ 5_100-400 ┆   ┆ 100-400ng ┆ 5_100-400 ┆ 100-400ng ┆ 2d5_100- │
│           ┆ g_D…      ┆ ng_…      ┆ ng_…      ┆   ┆ _B_…      ┆ ng_…      ┆ _D_…      ┆ 400ng_…  │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ P28834-32 ┆ 15.766823 ┆ 15.188649 ┆ 15.632032 ┆ … ┆ 15.240013 ┆ 15.292759 ┆ 15.477235 ┆ 15.41126 │
│ 5_326     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ P26321-20 ┆ 15.192827 ┆ 14.701852 ┆ 15.186824 ┆ … ┆ 14.775744 ┆ 14.66434  ┆ 14.965402 ┆ 14.99716 │
│ 7_208     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ P00558-30 ┆ 14.493324 ┆ 10.640626 ┆ 12.228858 ┆ … ┆ null      ┆ null      ┆ 12.376053 ┆ 11.02101 │
│ 4_305     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ P25043-16 ┆ 16.730922 ┆ 16.273255 ┆ 16.590449 ┆ … ┆ 16.541207 ┆ 16.340854 ┆ 16.645863 ┆ 16.43988 │
│ 4_165     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ Q08235-17 ┆ 11.992052 ┆ null      ┆ 12.237704 ┆ … ┆ 11.947107 ┆ 12.239447 ┆ 12.537958 ┆ null     │
│ 9_180     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ P07149-14 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 13.07184 │
│ 21_1422   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ P18621-11 ┆ 12.850573 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 8_119     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q6P1L5-40 ┆ 11.851798 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 6_407     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q5JRA6-12 ┆ null      ┆ 13.004103 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 38_1239   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ P21802-70 ┆ null      ┆ null      ┆ 12.698324 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0_701     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Prec quant df

In [ ]:
prec_qdf = lipana.convert_long_report_to_wide(
    report.df.filter(~pl.col("cut_site_is_restricted")),
    index_col="precursor",
    column_col="run",
    value_col="precursor_quantity",
    do_log_scale=2,
    do_unique=True,
    recollected_annotation_cols=None,
    strict_recollection=False,
)

# Stats

## Missing value

In [39]:
missing_value_handler_funcs = {
    "raw": functools.partial(
        lipana.do_missing_value_handling_on_df,
        config=None,
        filter_less_than_rep=2,
    ),
    "FillFullEmpty": functools.partial(
        lipana.do_missing_value_handling_on_df,
        config=lipana.FullEmptyFillingMissingValueHandler(min_rep_count=2),
        filter_less_than_rep=2,
    ),
    "FillFullEmpty_NormalDistSample": functools.partial(
        lipana.do_missing_value_handling_on_df,
        config=(
            lipana.FullEmptyFillingMissingValueHandler(min_rep_count=2),
            lipana.NormalDistSamplingMissingValueHandler(
                min_rep_count=2, do_imputation_for_rep_range=(1, 1), log_scale_minmax_diff=1
            ),
        ),
        filter_less_than_rep=2,
    ),
}

## FC

In [40]:
fc_configs = {
    "mean_div": lipana.RatioCalcConfig(
        cond_to_cols_map=exp_setting.condition_to_runs_map,
        base_cond="H5_Y100",
        cond_pairs=None,
        is_log=True,
        temp_reverse_log_scale=2,
        div_method="agg_and_divide",
        agg_method="mean",
        new_colname_pattern="log2_fc",
    )
}

## Stats

In [43]:
hypo_test_configs = {
    "limma_cut_site": lipana.LimmaConfig(
        annotation_data=exp_setting,
        entry_name="cut_site",
        condition_pairs="H5_Y100",
        output_column_map="default",
        output_column_map_override={"logFC": "log2_fc_limma", "adj.P.Val": "adj_pvalue_limma"},
        recollected_columns="log2_fc",
        dump_in_df_to=None,
        del_files=True,
    ),
    "limma_precursor": lipana.LimmaConfig(
        annotation_data=exp_setting,
        entry_name="precursor",
        condition_pairs="H5_Y100",
        output_column_map="default",
        output_column_map_override={"logFC": "log2_fc_limma", "adj.P.Val": "adj_pvalue_limma"},
        recollected_columns="log2_fc",
        dump_in_df_to=None,
        del_files=True,
    ),
}

## Sign

In [45]:
sign_voting_configs = {
    "t_sign_on_cut_site": lipana.SignVotingConfig(
        sign_value_col="t",
        group_col="cut_site",
        row_sign_col="row_sign",
        group_sign_col="group_sign",
        drop_opposite_sign=True,
        drop_bidirectional_balanced_group=True,
    ),
    "fc2p05_on_cut_site": lipana.SignVotingConfig(
        pos_sign_gt_col_value=(("log2_fc", np.log2(2)),),
        pos_sign_lt_col_value=(("pvalue", 0.05),),
        neg_sign_gt_col_value=None,
        neg_sign_lt_col_value=(("log2_fc", np.log2(1 / 2)), ("pvalue", 0.05)),
        group_col="cut_site",
        row_sign_col="row_sign",
        group_sign_col="group_sign",
        filter_value_col="pvalue",
    ),
    "fc1d5p05_on_cut_site": lipana.SignVotingConfig(
        pos_sign_gt_col_value=(("log2_fc", np.log2(1.5)),),
        pos_sign_lt_col_value=(("pvalue", 0.05),),
        neg_sign_gt_col_value=None,
        neg_sign_lt_col_value=(("log2_fc", np.log2(1 / 1.5)), ("pvalue", 0.05)),
        group_col="cut_site",
        row_sign_col="row_sign",
        group_sign_col="group_sign",
        filter_value_col="pvalue",
    ),
}


stats_agg_configs = {
    "fc_limmafc_p_adjp_cut_site": lipana.ValueAggregationConfig(
        group_col="cut_site",
        agg_col=("log2_fc", "log2_fc_limma", "pvalue", "adj_pvalue_limma"),
        agg_func=(
            np.nanmedian,
            np.nanmedian,
            lipana.scipy_comb_p_with_nan,
            lipana.scipy_comb_p_with_nan,
        ),
        recollected_columns=None,
    ),
}

## FDR

In [46]:
fdr_configs = {
    "exp_level": lipana.FDRConfig(
        group=None,
        pre_filter=None,
        p_col="pvalue",
        new_col_name="adj_pvalue_exp_level",
        method="BH",
    ),
    "protein_level": lipana.FDRConfig(
        group="protein_group",
        pre_filter=None,
        p_col="pvalue",
        new_col_name="adj_pvalue_protein_level",
        method="BH",
    ),
}

## On site

In [75]:
site_qdf

shape: (34_889, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cut_site  ┆ 20240404_ ┆ 20240331_ ┆ 20240404_ ┆ … ┆ 20240331_ ┆ 20240331_ ┆ 20240404_ ┆ 20240404 │
│ ---       ┆ YSJ-HY_25 ┆ YSJ-HY_7d ┆ YSJ-HY_7d ┆   ┆ YSJ-HY_5_ ┆ YSJ-HY_2d ┆ YSJ-HY_5_ ┆ _YSJ-HY_ │
│ str       ┆ _100-400n ┆ 5_100-400 ┆ 5_100-400 ┆   ┆ 100-400ng ┆ 5_100-400 ┆ 100-400ng ┆ 2d5_100- │
│           ┆ g_D…      ┆ ng_…      ┆ ng_…      ┆   ┆ _B_…      ┆ ng_…      ┆ _D_…      ┆ 400ng_…  │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ P28834-32 ┆ 15.766823 ┆ 15.188649 ┆ 15.632032 ┆ … ┆ 15.240013 ┆ 15.292759 ┆ 15.477235 ┆ 15.41126 │
│ 5_326     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ P26321-20 ┆ 15.192827 ┆ 14.701852 ┆ 15.186824 ┆ … ┆ 14.775744 ┆ 14.66434  ┆ 14.965402 ┆ 14.99716 │
│ 7_208     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ P00558-30 ┆ 14.493324 ┆ 10.640626 ┆ 12.228858 ┆ … ┆ null      ┆ null      ┆ 12.376053 ┆ 11.02101 │
│ 4_305     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ P25043-16 ┆ 16.730922 ┆ 16.273255 ┆ 16.590449 ┆ … ┆ 16.541207 ┆ 16.340854 ┆ 16.645863 ┆ 16.43988 │
│ 4_165     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ Q08235-17 ┆ 11.992052 ┆ null      ┆ 12.237704 ┆ … ┆ 11.947107 ┆ 12.239447 ┆ 12.537958 ┆ null     │
│ 9_180     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ P07149-14 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 13.07184 │
│ 21_1422   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ P18621-11 ┆ 12.850573 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 8_119     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q6P1L5-40 ┆ 11.851798 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 6_407     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q5JRA6-12 ┆ null      ┆ 13.004103 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 38_1239   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ P21802-70 ┆ null      ┆ null      ┆ 12.698324 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0_701     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [62]:
funcs = [
    functools.partial(
        missing_value_handler_funcs["FillFullEmpty"],
        exp_runs=exp_setting.condition_to_runs_map["H7d5_Y100"],
        ctrl_runs=exp_setting.condition_to_runs_map["H5_Y100"],
        annotation_col="cut_site",
    ),
    functools.partial(
        lipana.do_desc_summary_on_df,
        config=fc_configs["mean_div"],
    ),
    functools.partial(
        lipana.do_stats_on_df,
        exp_runs=exp_setting.condition_to_runs_map["H7d5_Y100"],
        ctrl_runs=exp_setting.condition_to_runs_map["H5_Y100"],
        config=hypo_test_configs["limma_cut_site"],
    ),
    functools.partial(
        lipana.attach_annotation_from_other_df,
        other_df=report.id_report,
        annotation_cols="protein_group",
        on="cut_site",
        method="leftjoin",
    ),
    functools.partial(
        lipana.do_stats_on_df,
        config=list(fdr_configs.values()),
    ),
]

In [63]:
site_stats = site_qdf.clone()
for func in funcs:
    site_stats = func(site_stats)

Quantification file: /tmp/tmpdixbwbd1.txt
All defined comparison pairs: c("H0_Y100", "H5_Y100")All defined comparison pairs: c("H2d5_Y100", "H5_Y100")All defined comparison pairs: c("H7d5_Y100", "H5_Y100")All defined comparison pairs: c("H25_Y100", "H5_Y100")
Available comparison pairs: c("H7d5_Y100", "H5_Y100")
Comparing H7d5_Y100 vs H5_Y100
Output to /tmp/tmpdixbwbd1.txt-limma_output.txt

In [64]:
site_stats

shape: (26_767, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cut_site  ┆ log2_fc_l ┆ AveExpr   ┆ t         ┆ … ┆ log2_fc   ┆ protein_g ┆ adj_pvalu ┆ adj_pval │
│ ---       ┆ imma      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ roup      ┆ e_exp_lev ┆ ue_prote │
│ str       ┆ ---       ┆ f64       ┆ f64       ┆   ┆ f32       ┆ ---       ┆ el        ┆ in_level │
│           ┆ f64       ┆           ┆           ┆   ┆           ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ P55957-75 ┆ 13.142081 ┆ 6.57104   ┆ 103.96809 ┆ … ┆ 13.142928 ┆ P55957    ┆ 1.6069e-1 ┆ 1.6992e- │
│ _76       ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆ 2         ┆ 15       │
│ Q8WX92-50 ┆ 13.790291 ┆ 6.895145  ┆ 101.55492 ┆ … ┆ 13.795383 ┆ Q8WX92    ┆ 1.6069e-1 ┆ 1.2820e- │
│ _51       ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆ 2         ┆ 15       │
│ P41567-48 ┆ 12.713923 ┆ 6.356961  ┆ 98.917003 ┆ … ┆ 12.715692 ┆ P41567    ┆ 1.6069e-1 ┆ 3.3147e- │
│ _49       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 15       │
│ Q32P28-13 ┆ 12.749259 ┆ 6.374629  ┆ 98.115714 ┆ … ┆ 12.751627 ┆ Q32P28    ┆ 1.6069e-1 ┆ 5.9807e- │
│ 2_133     ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 16       │
│ P78347-90 ┆ 12.688437 ┆ 6.344218  ┆ 97.340152 ┆ … ┆ 12.691032 ┆ P78347    ┆ 1.6069e-1 ┆ 9.6932e- │
│ _91       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ 15       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ P46680-14 ┆ -0.000076 ┆ 13.400194 ┆ -0.000304 ┆ … ┆ -0.001419 ┆ P46680    ┆ 0.999901  ┆ 0.999764 │
│ 4_145     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ P25037-25 ┆ -0.000038 ┆ 13.642886 ┆ -0.000198 ┆ … ┆ 0.00815   ┆ P25037    ┆ 0.999901  ┆ 0.999846 │
│ 3_254     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ P32327-34 ┆ -0.000044 ┆ 13.528285 ┆ -0.000187 ┆ … ┆ 0.003501  ┆ P32327    ┆ 0.999901  ┆ 0.999854 │
│ 5_346     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ P00330-19 ┆ -0.000047 ┆ 19.980889 ┆ -0.000176 ┆ … ┆ 0.003937  ┆ P00330    ┆ 0.999901  ┆ 0.999863 │
│ 9_200     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ P52910-50 ┆ -0.000002 ┆ 13.222528 ┆ -0.000009 ┆ … ┆ -0.022321 ┆ P52910    ┆ 0.999993  ┆ 0.999993 │
│ 4_505     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## On precursor

In [65]:
prec_qdf

shape: (40_363, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ precursor ┆ 20240331_ ┆ 20240404_ ┆ 20240404_ ┆ … ┆ 20240331_ ┆ 20240331_ ┆ 20240404_ ┆ 20240331 │
│ ---       ┆ YSJ-HY_7d ┆ YSJ-HY_25 ┆ YSJ-HY_5_ ┆   ┆ YSJ-HY_0_ ┆ YSJ-HY_2d ┆ YSJ-HY_0_ ┆ _YSJ-HY_ │
│ str       ┆ 5_100-400 ┆ _100-400n ┆ 100-400ng ┆   ┆ 100-400ng ┆ 5_100-400 ┆ 100-400ng ┆ 2d5_100- │
│           ┆ ng_…      ┆ g_D…      ┆ _D_…      ┆   ┆ _B_…      ┆ ng_…      ┆ _C_…      ┆ 400ng_…  │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GLVEPTQFA ┆ 13.635662 ┆ 15.509853 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ R/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LDLGGDSAG ┆ 12.851636 ┆ 14.906656 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ R/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SSGMKPFLT ┆ null      ┆ 14.23253  ┆ 13.278849 ┆ … ┆ 11.923843 ┆ 11.585978 ┆ 10.244216 ┆ 10.50108 │
│ LEGISAPLD ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ K/3       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VRHGQSEWN ┆ 18.677786 ┆ 18.033836 ┆ 17.987777 ┆ … ┆ 18.56716  ┆ 18.680011 ┆ 18.817253 ┆ 18.83286 │
│ EK/3      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ ATINIGTIG ┆ 13.517454 ┆ null      ┆ 13.152359 ┆ … ┆ 13.933735 ┆ 13.520398 ┆ 12.910175 ┆ 13.91128 │
│ HVAHGK/2  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ELDPLTGEW ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ HYK/2     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ EGTAVIDGE ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ FKELK/2   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ EIKDEAYSS ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ LR/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TVPFVPISG ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ WNGDNMIE/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LVQGKTDAV ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ NPENK/2   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [71]:
funcs = [
    functools.partial(
        missing_value_handler_funcs["FillFullEmpty"],
        exp_runs=exp_setting.condition_to_runs_map["H7d5_Y100"],
        ctrl_runs=exp_setting.condition_to_runs_map["H5_Y100"],
        annotation_col="precursor",
    ),
    functools.partial(
        lipana.do_desc_summary_on_df,
        config=fc_configs["mean_div"],
    ),
    functools.partial(
        lipana.do_stats_on_df,
        exp_runs=exp_setting.condition_to_runs_map["H7d5_Y100"],
        ctrl_runs=exp_setting.condition_to_runs_map["H5_Y100"],
        config=hypo_test_configs["limma_precursor"],
    ),
    functools.partial(
        lipana.attach_annotation_from_other_df,
        other_df=report.id_report,
        annotation_cols="cut_site",
        on="precursor",
        pre_filter=(~pl.col("cut_site_is_restricted")),
        method="leftjoin",
    ),
    functools.partial(
        lipana.do_stats_on_df,
        config=[
            sign_voting_configs["t_sign_on_cut_site"],
            stats_agg_configs["fc_limmafc_p_adjp_cut_site"],
        ],
    ),
    functools.partial(
        lipana.attach_annotation_from_other_df,
        other_df=report.id_report,
        annotation_cols="protein_group",
        on="cut_site",
        method="leftjoin",
    ),
    functools.partial(
        lipana.do_stats_on_df,
        config=list(fdr_configs.values()),
    ),
]

In [72]:
site_stats_from_prec = prec_qdf.clone()
for func in funcs:
    site_stats_from_prec = func(site_stats_from_prec)

Quantification file: /tmp/tmp5xhrijgq.txt
All defined comparison pairs: c("H0_Y100", "H5_Y100")All defined comparison pairs: c("H2d5_Y100", "H5_Y100")All defined comparison pairs: c("H7d5_Y100", "H5_Y100")All defined comparison pairs: c("H25_Y100", "H5_Y100")
Available comparison pairs: c("H7d5_Y100", "H5_Y100")
Comparing H7d5_Y100 vs H5_Y100
Output to /tmp/tmp5xhrijgq.txt-limma_output.txt